# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written mock of the microplate centrifuge feature. Like the other instrument mocks
# it exercises SiLA2 flows and follows the feature's status contract so it is a drop-in
# replacement for the real server (same Feature XML => same behaviour). Physical effects:
# OpenDoor/CloseDoor toggle this server's location accessibility; SpinCycle requires a
# plate present at the location.
#
# Status enum (property `Status`, common to all instruments): 0=Not Connected, 1=Idle,
# 2=Running, 3=Error. Per the XML contract, the actuating commands (OpenDoor, CloseDoor,
# SpinCycle, Home, Park, LoadPlate, UnloadPlate) are Running while they execute and return
# to Idle; Stop/Reset keep the status they started in; every command sets Error on failure.
# (Note the door commands ARE Running here, unlike the thermal cycler's lid commands, which
# its own XML keeps at Idle -- a per-feature exception there.)
from __future__ import annotations

import logging
import time
from datetime import timedelta
from queue import Queue
from typing import TYPE_CHECKING

from sila2.server import MetadataDict, ObservableCommandInstance

from ..generated.microplatecentrifugecontroller import (
    CloseDoor_Responses,
    EnumerateProfiles_Responses,
    Home_Responses,
    LoadPlate_Responses,
    MicroplateCentrifugeControllerBase,
    OpenDoor_Responses,
    Park_Responses,
    Reset_Responses,
    SpinCycle_Responses,
    StopSpinCycle_Responses,
    UnloadPlate_Responses,
)

if TYPE_CHECKING:
    from ..server import Server


logger = logging.getLogger(__name__)


class MicroplateCentrifugeControllerImpl(MicroplateCentrifugeControllerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._server = parent_server

        # Keep observable command instances alive well beyond their brief mock runtime so a
        # slow client can still poll them to completion.
        self.OpenDoor_default_lifetime_of_execution = timedelta(minutes=30)
        self.CloseDoor_default_lifetime_of_execution = timedelta(minutes=30)
        self.SpinCycle_default_lifetime_of_execution = timedelta(minutes=30)
        self.StopSpinCycle_default_lifetime_of_execution = timedelta(minutes=30)
        self.Reset_default_lifetime_of_execution = timedelta(minutes=30)
        self.Home_default_lifetime_of_execution = timedelta(minutes=30)
        self.Park_default_lifetime_of_execution = timedelta(minutes=30)
        self.LoadPlate_default_lifetime_of_execution = timedelta(minutes=30)
        self.UnloadPlate_default_lifetime_of_execution = timedelta(minutes=30)

        # Static version/profile readouts returned by the getter commands, plus which
        # bucket's door is currently open (0 = closed). Fixed mock values.
        self._active_x_version = "13.1.9.1493-mock"
        self._centrifuge_active_x_version = "13.1.9.1493-mock"
        self._centrifuge_hardware_version = "HW-MOCK-1"
        self._firmware_version = "FW-MOCK-1.0"
        self._hardware_version = "CEN-MOCK-1"
        self._profiles = ["default", "gentle_spin", "fast_spin"]
        self._door_bucket = 0

        # Status goes Not Connected (0) -> Idle (1) to mimic a real server coming online.
        self.update_Status(0)
        self.update_Status(1)

    def Status_on_subscription(self, *, metadata: MetadataDict) -> Queue[int] | None:
        # Emit the current status immediately to a new subscriber; fall back to Idle (1).
        queue = super().Status_on_subscription(metadata=metadata)
        try:
            self.update_Status(self.current_Status, queue=queue)
        except AttributeError:
            self.update_Status(1, queue=queue)
        return queue

    def _validate_bucket(self, bucket: int) -> None:
        # Buckets are numbered 1 and 2 on this mock.
        if bucket not in (1, 2):
            raise ValueError("BucketNumber must be 1 or 2")

    def _begin_running(self, instance: ObservableCommandInstance) -> None:
        # Start an actuating command: enter Running (2) for the duration of the motion
        # (spec: "Status while this command is running: Running").
        instance.begin_execution()
        self.update_Status(2)
        time.sleep(0.05)

    def _begin_quiet(self, instance: ObservableCommandInstance) -> None:
        # Start a command that keeps its start status (spec: "same as start"): Stop/Reset
        # do not assert Running.
        instance.begin_execution()
        time.sleep(0.05)

    # --- Version getters: static mock readouts, no status effect. ---

    def get_ActiveXVersion(self, *, metadata: MetadataDict) -> str:
        return self._active_x_version

    def get_CentrifugeActiveXVersion(self, *, metadata: MetadataDict) -> str:
        return self._centrifuge_active_x_version

    def get_CentrifugeHardwareVersion(self, *, metadata: MetadataDict) -> str:
        return self._centrifuge_hardware_version

    def get_FirmwareVersion(self, *, metadata: MetadataDict) -> str:
        return self._firmware_version

    def get_HardwareVersion(self, *, metadata: MetadataDict) -> str:
        return self._hardware_version

    def EnumerateProfiles(self, *, metadata: MetadataDict) -> EnumerateProfiles_Responses:
        # Unobservable query returning the mock profile names; leaves Status unchanged.
        logger.info("MicroplateCentrifugeController.EnumerateProfiles called")
        return EnumerateProfiles_Responses(self._profiles)

    def OpenDoor(
        self,
        BucketNumber: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> OpenDoor_Responses:
        # Physical effect: an open door makes this server's location accessible. Actuating,
        # so Running while moving, back to Idle on success, Error on failure. BucketNumber
        # is validated before execution starts (a bad value rejects without faulting).
        logger.info("MicroplateCentrifugeController.OpenDoor called: bucket_number=%s", BucketNumber)
        self._validate_bucket(BucketNumber)
        self._begin_running(instance)
        try:
            self._door_bucket = BucketNumber
            self._server.unlock_location(command_name="MicroplateCentrifugeController.OpenDoor")
            self.update_Status(1)  # normal -> Idle
            return OpenDoor_Responses()
        except Exception:
            self.update_Status(3)  # Error
            raise

    def CloseDoor(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> CloseDoor_Responses:
        # Inverse of OpenDoor: a closed door makes the location inaccessible.
        logger.info("MicroplateCentrifugeController.CloseDoor called")
        self._begin_running(instance)
        try:
            self._door_bucket = 0
            self._server.lock_location(command_name="MicroplateCentrifugeController.CloseDoor")
            self.update_Status(1)  # normal -> Idle
            return CloseDoor_Responses()
        except Exception:
            self.update_Status(3)  # Error
            raise

    def SpinCycle(
        self,
        VelocityPercent: float,
        AccelerationPercent: float,
        DecelerationPercent: float,
        TimerMode: int,
        Time: int,
        BucketNumberToLoad: int,
        BucketNumberToUnload: int,
        GripperOffsetToLoad: float,
        GripperOffsetToUnload: float,
        PlateHeightToLoad: float,
        PlateHeightToUnload: float,
        SpeedToLoad: int,
        SpeedToUnload: int,
        OptionsToLoad: int,
        OptionsToUnload: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> SpinCycle_Responses:
        # The spin itself: requires a plate present (checked before the run starts). Many
        # parameters are accepted for signature fidelity but not simulated. Actuating:
        # Running while spinning, Idle on success, Error on failure.
        logger.info(
            "MicroplateCentrifugeController.SpinCycle called: velocity_percent=%s acceleration_percent=%s "
            "deceleration_percent=%s timer_mode=%s time=%s bucket_number_to_load=%s bucket_number_to_unload=%s",
            VelocityPercent,
            AccelerationPercent,
            DecelerationPercent,
            TimerMode,
            Time,
            BucketNumberToLoad,
            BucketNumberToUnload,
        )
        if Time < 0:
            raise ValueError("Time must be >= 0")
        self._server.require_item_at_location(command_name="MicroplateCentrifugeController.SpinCycle")
        self._begin_running(instance)
        try:
            self.update_Status(1)  # normal -> Idle
            return SpinCycle_Responses()
        except Exception:
            self.update_Status(3)  # Error
            raise

    def StopSpinCycle(
        self,
        BucketNumber: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> StopSpinCycle_Responses:
        # Stop the spin. Runs while the instrument is Running (keeps that status), then
        # returns to Idle on success / Error on failure.
        logger.info("MicroplateCentrifugeController.StopSpinCycle called: bucket_number=%s", BucketNumber)
        self._validate_bucket(BucketNumber)
        self._begin_quiet(instance)
        try:
            self.update_Status(1)  # normal -> Idle
            return StopSpinCycle_Responses()
        except Exception:
            self.update_Status(3)  # Error
            raise

    def Reset(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Reset_Responses:
        # Recover to Idle (e.g. from Error). Keeps its start status during execution, then
        # Idle on success / Error on failure. Clears the door state.
        logger.info("MicroplateCentrifugeController.Reset called")
        self._begin_quiet(instance)
        try:
            self._door_bucket = 0
            self.update_Status(1)  # reset -> Idle
            return Reset_Responses()
        except Exception:
            self.update_Status(3)  # Error
            raise

    def Home(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Home_Responses:
        # Actuating motion command (return the rotor to its home position).
        logger.info("MicroplateCentrifugeController.Home called")
        self._begin_running(instance)
        try:
            self.update_Status(1)  # normal -> Idle
            return Home_Responses()
        except Exception:
            self.update_Status(3)  # Error
            raise

    def Park(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Park_Responses:
        # Actuating motion command (move the rotor to its park position).
        logger.info("MicroplateCentrifugeController.Park called")
        self._begin_running(instance)
        try:
            self.update_Status(1)  # normal -> Idle
            return Park_Responses()
        except Exception:
            self.update_Status(3)  # Error
            raise

    def LoadPlate(
        self,
        BucketNumber: int,
        GripperOffset: float,
        PlateHeight: float,
        Speed: int,
        Options: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> LoadPlate_Responses:
        # Actuating command: load a plate into a bucket. Parameters accepted for fidelity,
        # not simulated. BucketNumber validated before execution.
        logger.info(
            "MicroplateCentrifugeController.LoadPlate called: bucket_number=%s gripper_offset=%s plate_height=%s "
            "speed=%s options=%s",
            BucketNumber,
            GripperOffset,
            PlateHeight,
            Speed,
            Options,
        )
        self._validate_bucket(BucketNumber)
        self._begin_running(instance)
        try:
            self.update_Status(1)  # normal -> Idle
            return LoadPlate_Responses()
        except Exception:
            self.update_Status(3)  # Error
            raise

    def UnloadPlate(
        self,
        BucketNumber: int,
        GripperOffset: float,
        PlateHeight: float,
        Speed: int,
        Options: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> UnloadPlate_Responses:
        # Actuating command: unload a plate from a bucket. Parameters accepted for fidelity,
        # not simulated. BucketNumber validated before execution.
        logger.info(
            "MicroplateCentrifugeController.UnloadPlate called: bucket_number=%s gripper_offset=%s plate_height=%s "
            "speed=%s options=%s",
            BucketNumber,
            GripperOffset,
            PlateHeight,
            Speed,
            Options,
        )
        self._validate_bucket(BucketNumber)
        self._begin_running(instance)
        try:
            self.update_Status(1)  # normal -> Idle
            return UnloadPlate_Responses()
        except Exception:
            self.update_Status(3)  # Error
            raise
