# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

import time
from datetime import timedelta
from queue import Queue
from typing import TYPE_CHECKING, Optional

from sila2.server import MetadataDict, ObservableCommandInstance

from ..generated.microplatecentrifugecontroller import (
    CloseDoor_Responses,
    EnumerateProfiles_Responses,
    Home_Responses,
    LoadPlate_Responses,
    MicroplateCentrifugeControllerBase,
    OpenDoor_Responses,
    Park_Responses,
    Reset_Responses,
    SpinCycle_Responses,
    StopSpinCycle_Responses,
    UnloadPlate_Responses,
)

if TYPE_CHECKING:
    from ..server import Server


class MicroplateCentrifugeControllerImpl(MicroplateCentrifugeControllerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

        self.OpenDoor_default_lifetime_of_execution = timedelta(minutes=30)
        self.CloseDoor_default_lifetime_of_execution = timedelta(minutes=30)
        self.SpinCycle_default_lifetime_of_execution = timedelta(minutes=30)
        self.StopSpinCycle_default_lifetime_of_execution = timedelta(minutes=30)
        self.Reset_default_lifetime_of_execution = timedelta(minutes=30)
        self.Home_default_lifetime_of_execution = timedelta(minutes=30)
        self.Park_default_lifetime_of_execution = timedelta(minutes=30)
        self.LoadPlate_default_lifetime_of_execution = timedelta(minutes=30)
        self.UnloadPlate_default_lifetime_of_execution = timedelta(minutes=30)

        self._active_x_version = "13.1.9.1493-mock"
        self._centrifuge_active_x_version = "13.1.9.1493-mock"
        self._centrifuge_hardware_version = "HW-MOCK-1"
        self._firmware_version = "FW-MOCK-1.0"
        self._hardware_version = "CEN-MOCK-1"
        self._profiles = ["default", "gentle_spin", "fast_spin"]
        self._door_bucket = 0

        self.update_Status(0)
        self.update_Status(1)

    def Status_on_subscription(self, *, metadata: MetadataDict) -> Optional["Queue[int]"]:
        queue = super().Status_on_subscription(metadata=metadata)
        try:
            self.update_Status(self.current_Status, queue=queue)
        except AttributeError:
            self.update_Status(1, queue=queue)
        return queue

    def _validate_bucket(self, bucket: int) -> None:
        if bucket not in (1, 2):
            raise ValueError("BucketNumber must be 1 or 2")

    def _run_observable(self, instance: ObservableCommandInstance) -> None:
        instance.begin_execution()
        self.update_Status(2)
        time.sleep(0.05)

    def get_ActiveXVersion(self, *, metadata: MetadataDict) -> str:
        return self._active_x_version

    def get_CentrifugeActiveXVersion(self, *, metadata: MetadataDict) -> str:
        return self._centrifuge_active_x_version

    def get_CentrifugeHardwareVersion(self, *, metadata: MetadataDict) -> str:
        return self._centrifuge_hardware_version

    def get_FirmwareVersion(self, *, metadata: MetadataDict) -> str:
        return self._firmware_version

    def get_HardwareVersion(self, *, metadata: MetadataDict) -> str:
        return self._hardware_version

    def EnumerateProfiles(self, *, metadata: MetadataDict) -> EnumerateProfiles_Responses:
        return EnumerateProfiles_Responses(self._profiles)

    def OpenDoor(
        self,
        BucketNumber: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> OpenDoor_Responses:
        self._validate_bucket(BucketNumber)
        self._run_observable(instance)
        try:
            self._door_bucket = BucketNumber
            return OpenDoor_Responses()
        finally:
            self.update_Status(1)

    def CloseDoor(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> CloseDoor_Responses:
        self._run_observable(instance)
        try:
            self._door_bucket = 0
            return CloseDoor_Responses()
        finally:
            self.update_Status(1)

    def SpinCycle(
        self,
        VelocityPercent: float,
        AccelerationPercent: float,
        DecelerationPercent: float,
        TimerMode: int,
        Time: int,
        BucketNumberToLoad: int,
        BucketNumberToUnload: int,
        GripperOffsetToLoad: float,
        GripperOffsetToUnload: float,
        PlateHeightToLoad: float,
        PlateHeightToUnload: float,
        SpeedToLoad: int,
        SpeedToUnload: int,
        OptionsToLoad: int,
        OptionsToUnload: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> SpinCycle_Responses:
        if Time < 0:
            raise ValueError("Time must be >= 0")
        self._run_observable(instance)
        try:
            return SpinCycle_Responses()
        finally:
            self.update_Status(1)

    def StopSpinCycle(
        self,
        BucketNumber: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> StopSpinCycle_Responses:
        self._validate_bucket(BucketNumber)
        self._run_observable(instance)
        try:
            return StopSpinCycle_Responses()
        finally:
            self.update_Status(1)

    def Reset(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Reset_Responses:
        self._run_observable(instance)
        try:
            self._door_bucket = 0
            return Reset_Responses()
        finally:
            self.update_Status(1)

    def Home(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Home_Responses:
        self._run_observable(instance)
        try:
            return Home_Responses()
        finally:
            self.update_Status(1)

    def Park(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Park_Responses:
        self._run_observable(instance)
        try:
            return Park_Responses()
        finally:
            self.update_Status(1)

    def LoadPlate(
        self,
        BucketNumber: int,
        GripperOffset: float,
        PlateHeight: float,
        Speed: int,
        Options: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> LoadPlate_Responses:
        self._validate_bucket(BucketNumber)
        self._run_observable(instance)
        try:
            return LoadPlate_Responses()
        finally:
            self.update_Status(1)

    def UnloadPlate(
        self,
        BucketNumber: int,
        GripperOffset: float,
        PlateHeight: float,
        Speed: int,
        Options: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> UnloadPlate_Responses:
        self._validate_bucket(BucketNumber)
        self._run_observable(instance)
        try:
            return UnloadPlate_Responses()
        finally:
            self.update_Status(1)
