# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written mock of the Station "Provider" feature -- a minimal server with only a
# Reset command and a Status property. Unlike the instrument controllers, this Provider's
# Feature XML does NOT document per-command status transitions, so this mock is not held to
# a status contract here; it just exposes Status and a Reset that returns to Idle.
#
# Status enum for the Provider features (property `Status`): 1=Idle, 2=Running, 3=Error,
# 4=Starting (note: different from the instrument controllers' 0=Not Connected/1=Idle/...).
from __future__ import annotations

import logging
from datetime import timedelta
from queue import Queue
from typing import TYPE_CHECKING

from sila2.server import MetadataDict, ObservableCommandInstance

from ..generated.stationprovider import Reset_Responses, StationProviderBase

if TYPE_CHECKING:
    from ..server import Server


logger = logging.getLogger(__name__)


class StationProviderImpl(StationProviderBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

        # Keep the Reset instance pollable well beyond its brief runtime.
        self.Reset_default_lifetime_of_execution = timedelta(minutes=30)

        # Startup status sequence Starting (4) -> Idle (1) -> Error (3). This intentionally
        # leaves the server reporting Error at boot AS A DEBUGGING AID: it lets clients
        # exercise error-handling and the Reset recovery path without first driving a real
        # failure. A client must call Reset to reach Idle. Kept deliberately (not a bug).
        self.update_Status(4)
        self.update_Status(1)
        self.update_Status(3)

    def Status_on_subscription(self, *, metadata: MetadataDict) -> Queue[int] | None:
        # Emit the current status immediately to a new subscriber; fall back to Idle (1).
        queue = super().Status_on_subscription(metadata=metadata)
        try:
            self.update_Status(self.current_Status, queue=queue)
        except AttributeError:
            self.update_Status(1, queue=queue)
        return queue

    def Reset(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> Reset_Responses:
        # Reset brings the station back to Idle (the recovery path from the Error boot state).
        logger.info("StationProvider.Reset called")
        instance.begin_execution()
        self.update_Status(1)
        return Reset_Responses()
