# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

import time
from datetime import timedelta
import logging
from queue import Queue
from typing import TYPE_CHECKING, Optional

from sila2.server import MetadataDict, ObservableCommandInstance

from ..generated.automatedthermalcyclercontroller import (
    AutomatedThermalCyclerControllerBase,
    CloseLid_Responses,
    GetInstrumentState_Responses,
    Load_Responses,
    OpenLid_Responses,
    Reset_Responses,
    StartRun_Responses,
    StopRun_Responses,
    Validate_Responses,
)

if TYPE_CHECKING:
    from ..server import Server


logger = logging.getLogger(__name__)


class AutomatedThermalCyclerControllerImpl(AutomatedThermalCyclerControllerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._server = parent_server

        self.Load_default_lifetime_of_execution = timedelta(minutes=30)
        self.Validate_default_lifetime_of_execution = timedelta(minutes=30)
        self.OpenLid_default_lifetime_of_execution = timedelta(minutes=30)
        self.CloseLid_default_lifetime_of_execution = timedelta(minutes=30)
        self.StartRun_default_lifetime_of_execution = timedelta(minutes=30)
        self.StopRun_default_lifetime_of_execution = timedelta(minutes=30)
        self.Reset_default_lifetime_of_execution = timedelta(minutes=30)

        self._protocol_loaded = False
        self._protocol_validated = False
        self._run_active = False

        self.update_ElapsedTime("00:00:00")
        self.update_RemainingTime("00:00:00")
        self.update_Status(0)
        self.update_Status(1)

    def Status_on_subscription(self, *, metadata: MetadataDict) -> Optional["Queue[int]"]:
        queue = super().Status_on_subscription(metadata=metadata)
        try:
            self.update_Status(self.current_Status, queue=queue)
        except AttributeError:
            self.update_Status(1, queue=queue)
        return queue

    def GetInstrumentState(self, *, metadata: MetadataDict) -> GetInstrumentState_Responses:
        logger.info("AutomatedThermalCyclerController.GetInstrumentState called")
        state = 1 if self._run_active else 0
        return GetInstrumentState_Responses(state)

    def Load(
        self,
        ProtocolFileData: bytes,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Load_Responses:
        logger.info("AutomatedThermalCyclerController.Load called: protocol_size=%s", len(ProtocolFileData))
        instance.begin_execution()
        self.update_Status(2)
        try:
            if not ProtocolFileData:
                raise ValueError("ProtocolFileData must not be empty")
            time.sleep(0.05)
            self._protocol_loaded = True
            self._protocol_validated = False
            return Load_Responses()
        finally:
            self.update_Status(1)

    def Validate(
        self,
        MaxSampleVolume: float,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Validate_Responses:
        logger.info("AutomatedThermalCyclerController.Validate called: max_sample_volume=%s", MaxSampleVolume)
        instance.begin_execution()
        self.update_Status(2)
        try:
            if MaxSampleVolume < 0:
                raise ValueError("MaxSampleVolume must be >= 0")
            if not self._protocol_loaded:
                raise RuntimeError("Load must be executed before Validate in this mock")
            time.sleep(0.05)
            self._protocol_validated = True
            return Validate_Responses()
        finally:
            self.update_Status(1)

    def OpenLid(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> OpenLid_Responses:
        logger.info("AutomatedThermalCyclerController.OpenLid called")
        instance.begin_execution()
        self.update_Status(2)
        try:
            time.sleep(0.05)
            return OpenLid_Responses()
        finally:
            self.update_Status(1)

    def CloseLid(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> CloseLid_Responses:
        logger.info("AutomatedThermalCyclerController.CloseLid called")
        instance.begin_execution()
        self.update_Status(2)
        try:
            time.sleep(0.05)
            return CloseLid_Responses()
        finally:
            self.update_Status(1)

    def StartRun(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> StartRun_Responses:
        logger.info("AutomatedThermalCyclerController.StartRun called")
        self._server.require_item_at_location(command_name="AutomatedThermalCyclerController.StartRun")
        instance.begin_execution()
        self.update_Status(2)
        try:
            if not self._protocol_validated:
                raise RuntimeError("Validate must be executed before StartRun in this mock")
            self._run_active = True
            self.update_ElapsedTime("00:00:00")
            self.update_RemainingTime("00:02:00")
            time.sleep(0.05)
            return StartRun_Responses()
        except Exception:
            self._run_active = False
            self.update_Status(1)
            raise

    def StopRun(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> StopRun_Responses:
        logger.info("AutomatedThermalCyclerController.StopRun called")
        instance.begin_execution()
        self.update_Status(2)
        try:
            self._run_active = False
            self.update_ElapsedTime("00:00:10")
            self.update_RemainingTime("00:00:00")
            time.sleep(0.05)
            return StopRun_Responses()
        finally:
            self.update_Status(1)

    def Reset(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Reset_Responses:
        logger.info("AutomatedThermalCyclerController.Reset called")
        instance.begin_execution()
        self.update_Status(2)
        try:
            self._protocol_loaded = False
            self._protocol_validated = False
            self._run_active = False
            self.update_ElapsedTime("00:00:00")
            self.update_RemainingTime("00:00:00")
            time.sleep(0.05)
            return Reset_Responses()
        finally:
            self.update_Status(1)
