# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written mock of the thermal cycler feature: enough behaviour to exercise SiLA2
# connect/command/state flows, not real instrument control. It keeps a little internal
# state (protocol loaded/validated, run active), drives the world model for the physical
# effects it has (lid open/close = location accessibility; StartRun requires a plate),
# and follows the feature's status contract so it is a drop-in replacement for the real
# instrument server (same Feature XML => same observable behaviour).
#
# Two DISTINCT status enums live in the (immutable) Feature contract; do not conflate:
#   * `Status` property (common to all instruments): 0=Not Connected, 1=Idle, 2=Running,
#     3=Error. This is what `update_Status(...)` sets.
#   * `InstrumentState` (the GetInstrumentState response, thermal-cycler specific):
#     0=IDLE, 1=STANDBY, 2=RUNNING, 3=ERROR, 4=DIAGNOSTICS.
# Per-command status transitions below follow the XML descriptions: non-run commands keep
# the start status (Idle) and only move to Error on failure; StartRun goes to Running and
# stays there; StopRun ends at Idle; any command failure sets Error.
# NOTE: this feature deliberately keeps OpenLid/CloseLid at the start status (Idle),
# unlike sibling instruments whose actuating commands are Running while moving (e.g. the
# centrifuge's OpenDoor/CloseDoor). That is an intentional per-feature exception in the
# (immutable) Feature XML -- not a mock bug -- so only StartRun ever sets Status Running.
from __future__ import annotations

import time
from datetime import timedelta
import logging
from queue import Queue
from typing import TYPE_CHECKING, Optional

from sila2.server import MetadataDict, ObservableCommandInstance

from ..generated.automatedthermalcyclercontroller import (
    AutomatedThermalCyclerControllerBase,
    CloseLid_Responses,
    GetInstrumentState_Responses,
    Load_Responses,
    OpenLid_Responses,
    Reset_Responses,
    StartRun_Responses,
    StopRun_Responses,
    Validate_Responses,
)

if TYPE_CHECKING:
    from ..server import Server


logger = logging.getLogger(__name__)


class AutomatedThermalCyclerControllerImpl(AutomatedThermalCyclerControllerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._server = parent_server

        # Keep observable command instances alive for 30 min (well beyond their brief mock
        # runtime) so a slow client can still poll them to completion.
        self.Load_default_lifetime_of_execution = timedelta(minutes=30)
        self.Validate_default_lifetime_of_execution = timedelta(minutes=30)
        self.OpenLid_default_lifetime_of_execution = timedelta(minutes=30)
        self.CloseLid_default_lifetime_of_execution = timedelta(minutes=30)
        self.StartRun_default_lifetime_of_execution = timedelta(minutes=30)
        self.StopRun_default_lifetime_of_execution = timedelta(minutes=30)
        self.Reset_default_lifetime_of_execution = timedelta(minutes=30)

        # Internal logical state. A protocol must be loaded then validated before a run;
        # `_run_active` tracks whether a run is in progress (reported by GetInstrumentState).
        self._protocol_loaded = False
        self._protocol_validated = False
        self._run_active = False

        # Seed the observable properties. Status goes Not Connected (0) -> Idle (1) to
        # mimic a real server coming online; Elapsed/Remaining start at zero.
        self.update_ElapsedTime("00:00:00")
        self.update_RemainingTime("00:00:00")
        self.update_Status(0)
        self.update_Status(1)

    def Status_on_subscription(self, *, metadata: MetadataDict) -> Optional["Queue[int]"]:
        # On a new subscription, immediately emit the current status so the subscriber does
        # not have to wait for the next change. Fall back to Idle (1) if none set yet.
        queue = super().Status_on_subscription(metadata=metadata)
        try:
            self.update_Status(self.current_Status, queue=queue)
        except AttributeError:
            self.update_Status(1, queue=queue)
        return queue

    def GetInstrumentState(self, *, metadata: MetadataDict) -> GetInstrumentState_Responses:
        # Unobservable read returning the `InstrumentState` enum (NOT the Status enum):
        # 2=RUNNING while a run is active, else 0=IDLE. A value-returning command (unlike
        # the side-effect commands below); leaves the Status property unchanged.
        logger.info("AutomatedThermalCyclerController.GetInstrumentState called")
        state = 2 if self._run_active else 0
        return GetInstrumentState_Responses(state)

    def Load(
        self,
        ProtocolFileData: bytes,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Load_Responses:
        # Load a protocol. Marks loaded (and invalidates any prior validation). Per the
        # contract the Status stays at its start value (Idle) throughout; only a failure
        # moves it to Error. Observability comes from the command instance, not Status.
        logger.info("AutomatedThermalCyclerController.Load called: protocol_size=%s", len(ProtocolFileData))
        instance.begin_execution()
        try:
            if not ProtocolFileData:
                raise ValueError("ProtocolFileData must not be empty")
            time.sleep(0.05)
            self._protocol_loaded = True
            self._protocol_validated = False
            return Load_Responses()
        except Exception:
            self.update_Status(3)  # Error
            raise

    def Validate(
        self,
        MaxSampleVolume: float,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Validate_Responses:
        # Validate the loaded protocol. Enforces the mock ordering Load -> Validate -> run.
        # Status stays Idle during; a failure moves it to Error.
        logger.info("AutomatedThermalCyclerController.Validate called: max_sample_volume=%s", MaxSampleVolume)
        instance.begin_execution()
        try:
            if MaxSampleVolume < 0:
                raise ValueError("MaxSampleVolume must be >= 0")
            if not self._protocol_loaded:
                raise RuntimeError("Load must be executed before Validate in this mock")
            time.sleep(0.05)
            self._protocol_validated = True
            return Validate_Responses()
        except Exception:
            self.update_Status(3)  # Error
            raise

    def OpenLid(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> OpenLid_Responses:
        # Physical effect: an open lid makes this server's location accessible (a plate can
        # be placed/removed). Pushed to the world model via the parent server. Status stays
        # Idle during; a failure moves it to Error.
        logger.info("AutomatedThermalCyclerController.OpenLid called")
        instance.begin_execution()
        try:
            time.sleep(0.05)
            self._server.unlock_location(command_name="AutomatedThermalCyclerController.OpenLid")
            return OpenLid_Responses()
        except Exception:
            self.update_Status(3)  # Error
            raise

    def CloseLid(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> CloseLid_Responses:
        # Inverse of OpenLid: a closed lid makes the location inaccessible. Status stays
        # Idle during; a failure moves it to Error.
        logger.info("AutomatedThermalCyclerController.CloseLid called")
        instance.begin_execution()
        try:
            time.sleep(0.05)
            self._server.lock_location(command_name="AutomatedThermalCyclerController.CloseLid")
            return CloseLid_Responses()
        except Exception:
            self.update_Status(3)  # Error
            raise

    def StartRun(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> StartRun_Responses:
        # Start a run. The occupancy precondition is checked BEFORE begin_execution, so a
        # missing plate rejects the command (status untouched, still Idle) without ever
        # entering Running. Once running, Status stays Running after this command returns
        # (the run continues until StopRun); on error it goes to Error, per the contract.
        logger.info("AutomatedThermalCyclerController.StartRun called")
        self._server.require_item_at_location(command_name="AutomatedThermalCyclerController.StartRun")
        instance.begin_execution()
        self.update_Status(2)  # Running (stays Running after this command returns)
        try:
            if not self._protocol_validated:
                raise RuntimeError("Validate must be executed before StartRun in this mock")
            self._run_active = True
            self.update_ElapsedTime("00:00:00")
            self.update_RemainingTime("00:02:00")
            time.sleep(0.05)
            return StartRun_Responses()
        except Exception:
            self._run_active = False
            self.update_Status(3)  # Error (spec: on error -> Error)
            raise

    def StopRun(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> StopRun_Responses:
        # End the run: clear the active flag and zero the remaining time. StopRun runs
        # while the instrument is Running (StartRun left it there), so it does not re-set
        # Running; on normal completion Status -> Idle, on error -> Error (per contract).
        logger.info("AutomatedThermalCyclerController.StopRun called")
        instance.begin_execution()
        try:
            self._run_active = False
            self.update_ElapsedTime("00:00:10")
            self.update_RemainingTime("00:00:00")
            time.sleep(0.05)
            self.update_Status(1)  # normal completion -> Idle
            return StopRun_Responses()
        except Exception:
            self.update_Status(3)  # Error
            raise

    def Reset(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Reset_Responses:
        # Return all internal state to power-on defaults. Reset recovers from Error: on
        # normal completion Status -> Idle, on error -> Error (per contract). It does not
        # assert Running.
        logger.info("AutomatedThermalCyclerController.Reset called")
        instance.begin_execution()
        try:
            self._protocol_loaded = False
            self._protocol_validated = False
            self._run_active = False
            self.update_ElapsedTime("00:00:00")
            self.update_RemainingTime("00:00:00")
            time.sleep(0.05)
            self.update_Status(1)  # reset -> Idle
            return Reset_Responses()
        except Exception:
            self.update_Status(3)  # Error
            raise
