# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

from datetime import timedelta
from queue import Queue
from typing import Optional, TYPE_CHECKING

from sila2.server import MetadataDict, ObservableCommandInstance

from ..generated.trolleyarmprovider import Reset_Responses, SetTrolleyPosition_Responses, TrolleyArmProviderBase

if TYPE_CHECKING:
    from ..server import Server


class TrolleyArmProviderImpl(TrolleyArmProviderBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

        # Default lifetime of observable command instances. Possible values:
        # None: Command instance is valid and stored in memory until server shutdown
        # datetime.timedelta: Command instance is deleted after this duration, can be increased during command runtime
        self.Reset_default_lifetime_of_execution = timedelta(minutes=30)

        # Initialize status as Starting -> Idle -> Error for testing flows.
        self.update_Status(4)
        self.update_Status(1)
        self.update_Status(3)

        # Trolley starts at rail position 0.
        self.update_TrolleyPosition(0)

    def Status_on_subscription(self, *, metadata: MetadataDict) -> Optional["Queue[int]"]:
        # Send the latest status immediately to the subscriber.
        queue = super().Status_on_subscription(metadata=metadata)
        try:
            self.update_Status(self.current_Status, queue=queue)
        except AttributeError:
            # If no status was set yet, start with Idle
            self.update_Status(1, queue=queue)
        return queue

    def Reset(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> Reset_Responses:
        # set execution status from `waiting` to `running`
        instance.begin_execution()

        # Reset brings the station back to Idle.
        self.update_Status(1)

        instance.complete()
        return Reset_Responses()

    def TrolleyPosition_on_subscription(self, *, metadata: MetadataDict) -> Optional["Queue[int]"]:
        # Send the latest trolley position immediately to the subscriber.
        queue = super().TrolleyPosition_on_subscription(metadata=metadata)
        try:
            self.update_TrolleyPosition(self.current_TrolleyPosition, queue=queue)
        except AttributeError:
            self.update_TrolleyPosition(0, queue=queue)
        return queue

    def SetTrolleyPosition(self, Position: int, *, metadata: MetadataDict) -> SetTrolleyPosition_Responses:
        if Position < 0:
            raise ValueError("Position must be a natural number (>= 0)")

        self.update_TrolleyPosition(Position)
        return SetTrolleyPosition_Responses()
