# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written mock of the trolley arm "Provider" feature. Pick and Place move an item in
# the shared world model THROUGH the arm's own location (Pick: source -> arm; Place: arm ->
# destination), via the parent server's helpers. This feature's Feature XML does NOT
# document per-command status transitions, so the status handling here is the mock's own
# choice (not a contract): actuating commands require the arm to be Idle first, go Running
# while moving, return to Idle on success, and -- for consistency with the instrument
# controllers -- go to Error on a failure during execution.
#
# Status enum for the Provider features (property `Status`): 1=Idle, 2=Running, 3=Error,
# 4=Starting.
from __future__ import annotations

import functools
import logging
from collections.abc import Callable
from datetime import timedelta
from queue import Queue
from typing import TYPE_CHECKING, Any

from sila2.server import MetadataDict, ObservableCommandInstance

from ..generated.trolleyarmprovider import (
    Pick_Responses,
    Place_Responses,
    Reset_Responses,
    SetTrolleyPosition_Responses,
    TrolleyArmProviderBase,
)

if TYPE_CHECKING:
    from ..server import Server


logger = logging.getLogger(__name__)


def _one_at_a_time(method: Callable[..., Any]) -> Callable[..., Any]:
    """Refuse to start this command while another one is executing on this server.

    A decorator rather than a `with` block inside every command body: the guard is a property of
    the command rather than four more lines of it, and the command name comes from the method
    itself instead of being repeated. Safe because sila2 invokes an implementation method without
    inspecting its signature.

    Commands whose job is to stop something are deliberately NOT decorated -- making them wait for
    the thing they exist to end would be backwards."""

    @functools.wraps(method)
    def wrapper(self: Any, *args: Any, **kwargs: Any) -> Any:
        with self.parent_server.executing(method.__name__):
            return method(self, *args, **kwargs)

    return wrapper


class TrolleyArmProviderImpl(TrolleyArmProviderBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

        # Keep the Reset instance pollable well beyond its brief runtime.
        self.Reset_default_lifetime_of_execution = timedelta(minutes=30)

        # Startup status Starting (4) -> Idle (1); the trolley starts at rail position 0.
        self.update_Status(4)
        self.update_Status(1)
        self.update_TrolleyPosition(0)

    def Status_on_subscription(self, *, metadata: MetadataDict) -> Queue[int] | None:
        # Emit the current status immediately to a new subscriber; fall back to Idle (1).
        queue = super().Status_on_subscription(metadata=metadata)
        try:
            self.update_Status(self.current_Status, queue=queue)
        except AttributeError:
            self.update_Status(1, queue=queue)
        return queue

    def Reset(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> Reset_Responses:
        # Reset brings the arm back to Idle.
        logger.info("TrolleyArmProvider.Reset called")
        instance.begin_execution()
        self.update_Status(1)
        return Reset_Responses()

    def TrolleyPosition_on_subscription(self, *, metadata: MetadataDict) -> Queue[int] | None:
        # Emit the current rail position immediately to a new subscriber; fall back to 0.
        queue = super().TrolleyPosition_on_subscription(metadata=metadata)
        try:
            self.update_TrolleyPosition(self.current_TrolleyPosition, queue=queue)
        except AttributeError:
            self.update_TrolleyPosition(0, queue=queue)
        return queue

    @_one_at_a_time
    def SetTrolleyPosition(self, Position: int, *, metadata: MetadataDict) -> SetTrolleyPosition_Responses:
        # Move the trolley along its rail. Requires the arm to be Idle; Running while it
        # moves, then back to Idle. (Unobservable command; the Status property is the only
        # progress signal, so the Idle -> Running -> Idle bracket is kept.)
        logger.info("TrolleyArmProvider.SetTrolleyPosition called: position=%s", Position)

        if Position < 0:
            raise ValueError("Position must be a natural number (>= 0)")

        if self.current_Status != 1:
            raise RuntimeError("SetTrolleyPosition can only be executed while status is Idle (1)")

        self.update_Status(2)
        try:
            # Keep Running long enough to be observable by polling clients.
            self.parent_server.sleep_for("SetTrolleyPosition")
            self.update_TrolleyPosition(Position)
            self.update_Status(1)  # normal -> Idle
            return SetTrolleyPosition_Responses()
        except Exception:
            self.update_Status(3)  # Error
            raise

    def Pick(self, LocationSpecifier: str, *, metadata: MetadataDict) -> Pick_Responses:
        # Pick: move the item from `LocationSpecifier` onto the arm's own location (the
        # transient holding spot). Requires Idle; Running while moving, then Idle.
        logger.info("TrolleyArmProvider.Pick called: location_specifier=%s", LocationSpecifier)

        if self.current_Status != 1:
            raise RuntimeError("Pick can only be executed while status is Idle (1)")

        self.update_Status(2)
        try:
            self.parent_server.pick_item(command_name="TrolleyArmProvider.Pick", location=LocationSpecifier)
            self.update_Status(1)  # normal -> Idle
            return Pick_Responses()
        except Exception:
            self.update_Status(3)  # Error (e.g. the world-model move failed)
            raise

    def Place(self, LocationSpecifier: str, *, metadata: MetadataDict) -> Place_Responses:
        # Place: move the item from the arm's own location to `LocationSpecifier`. Requires
        # Idle; Running while moving, then Idle. (Pick then Place = a full transfer.)
        logger.info("TrolleyArmProvider.Place called: location_specifier=%s", LocationSpecifier)

        if self.current_Status != 1:
            raise RuntimeError("Place can only be executed while status is Idle (1)")

        self.update_Status(2)
        try:
            self.parent_server.place_item(command_name="TrolleyArmProvider.Place", location=LocationSpecifier)
            self.update_Status(1)  # normal -> Idle
            return Place_Responses()
        except Exception:
            self.update_Status(3)  # Error (e.g. the world-model move failed)
            raise
