x-sila2-server: &sila2-server
  build:
    context: ./servers/station_server
    dockerfile: Dockerfile
  depends_on:
    - laboratory-model
  environment:
    - PYTHONUNBUFFERED=1
    - SILA_SERVER_TYPE=StationServer
  command: ["python", "-m", "station_server", "--ip-address", "0.0.0.0", "--port", "50052", "--insecure", "--verbose", "--laboratory-model-url", "http://laboratory-model:8001", "--laboratory-model-location", "station:1"]

x-trolley-arm-server: &trolley-arm-server
  build:
    context: ./servers/trolley_arm_server
    dockerfile: Dockerfile
  depends_on:
    - laboratory-model
  environment:
    - PYTHONUNBUFFERED=1
    - SILA_SERVER_TYPE=TrolleyArmServer
  command: ["python", "-m", "trolley_arm_server", "--ip-address", "0.0.0.0", "--port", "50052", "--insecure", "--verbose", "--laboratory-model-url", "http://laboratory-model:8001", "--laboratory-model-location", "trolley-arm:1"]

x-microplate-centrifuge-server: &microplate-centrifuge-server
  build:
    context: ./servers/microplate_centrifuge_server
    dockerfile: Dockerfile
  depends_on:
    - laboratory-model
  environment:
    - PYTHONUNBUFFERED=1
    - SILA_SERVER_TYPE=MicroplateCentrifugeServer
  command: ["python", "-m", "microplate_centrifuge_server", "--ip-address", "0.0.0.0", "--port", "50052", "--insecure", "--verbose", "--laboratory-model-url", "http://laboratory-model:8001", "--laboratory-model-location", "centrifuge:1"]

x-plateloc-server: &plateloc-server
  build:
    context: ./servers/plateloc_server
    dockerfile: Dockerfile
  depends_on:
    - laboratory-model
  environment:
    - PYTHONUNBUFFERED=1
    - SILA_SERVER_TYPE=PlateLocServer
  command: ["python", "-m", "plateloc_server", "--ip-address", "0.0.0.0", "--port", "50052", "--insecure", "--verbose", "--laboratory-model-url", "http://laboratory-model:8001", "--laboratory-model-location", "plateloc:1"]

x-plate-seal-remover-server: &plate-seal-remover-server
  build:
    context: ./servers/automated_plate_seal_remover_server
    dockerfile: Dockerfile
  depends_on:
    - laboratory-model
  environment:
    - PYTHONUNBUFFERED=1
    - SILA_SERVER_TYPE=AutomatedPlateSealRemoverServer
  command: ["python", "-m", "automated_plate_seal_remover_server", "--ip-address", "0.0.0.0", "--port", "50052", "--insecure", "--verbose", "--laboratory-model-url", "http://laboratory-model:8001", "--laboratory-model-location", "seal-remover:1"]

x-thermal-cycler-server: &thermal-cycler-server
  build:
    context: ./servers/automated_thermal_cycler_server
    dockerfile: Dockerfile
  depends_on:
    - laboratory-model
  environment:
    - PYTHONUNBUFFERED=1
    - SILA_SERVER_TYPE=AutomatedThermalCyclerServer
  command: ["python", "-m", "automated_thermal_cycler_server", "--ip-address", "0.0.0.0", "--port", "50052", "--insecure", "--verbose", "--laboratory-model-url", "http://laboratory-model:8001", "--laboratory-model-location", "thermal-cycler:1"]

services:
  laboratory-model:
    build:
      context: ./laboratory_model
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - LABORATORY_MODEL_INITIAL_STATE_FILE=/app/config/initial_state.json
    volumes:
      - ./config/laboratory_model.initial_state.json:/app/config/initial_state.json:ro

  sila2-server-1:
    <<: *microplate-centrifuge-server
    ports:
      - "50052:50052"
    environment:
      - SILA_SERVER_NAME=Agilent-Microplate-Centrifuge

  sila2-server-2:
    <<: *plateloc-server
    ports:
      - "50053:50052"
    environment:
      - SILA_SERVER_NAME=Agilent-PlateLoc

  sila2-server-3:
    <<: *plate-seal-remover-server
    ports:
      - "50054:50052"
    environment:
      - SILA_SERVER_NAME=Azenta-Automated-Plate-Seal-Remover

  sila2-server-4:
    <<: *thermal-cycler-server
    ports:
      - "50055:50052"
    environment:
      - SILA_SERVER_NAME=ThermoFisher-Thermal-Cycler

  sila2-server-5:
    <<: *sila2-server
    ports:
      - "50056:50052"
    environment:
      - SILA_SERVER_NAME=Tecan-Fluent

  trolley-arm-server-1:
    <<: *trolley-arm-server
    ports:
      - "50057:50052"
    environment:
      - SILA_SERVER_NAME=Trolley-Arm-Server
