# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written beyond the codegen scaffold. This is the mock of Ardea, a real machine whose
# SiLA2 server (`ardea-sila2`) drives a DENSO robot arm on a travel carriage over ORiN b-CAP
# and a KEYENCE PLC over the KV COM+ Library. It replaced the trolley arm as this lab's
# transporter, and it is the one server here whose Feature definitions come from a real
# instrument -- all nine of them, unchanged, so a workflow written against this mock can be
# pointed at the machine (see `specs/ardea_server/README.md`).
#
# WHAT IS MOCKED AND WHAT IS NOT. Only `LabwareService.Transfer` performs work, because it is
# the one command a workflow needs from a transporter: carry a labware from one station to
# another. Everything else the real server offers -- the individual pick and put, the carriage
# and hand actuators, the pose checks, and the two providers' low-level variable/task/PLC
# access -- raises NotImplementedError, which SiLA reports as an undefined execution error.
# That is a deliberate floor rather than an unfinished state: those commands drive hardware
# this world model has no counterpart for, and a mock that pretended to run them would let a
# workflow come to depend on behaviour nothing here checks. The Feature definitions still
# declare them, which is what keeps the swap with the real server possible.
#
# Three read-only properties DO answer, because the world model already holds what they
# report: the station names, the carriage position, and the machine light. Each one's
# derivation is explained at the helper that computes it, below.
#
# The transfer itself is two world-model moves through the arm's own location
# (`laboratory_model_location`): source -> arm, then arm -> destination. The arm holding the
# plate mid-route is a real state on the machine, so it is a real state here too. As with the
# trolley arm before it, the world model has to be configured for this server to work at all:
# a transfer that does not reach it has not happened.
#
# The HTTP mechanics live in the shared `laboratory_client`; what the world *means* stays
# here, which is this environment's standing split (`docs/RULES.md`).

import json
import logging
import os
import time
from collections.abc import Iterator
from contextlib import contextmanager
from threading import Lock
from uuid import UUID, uuid4

from sila2.server import SilaServer

from laboratory_client import LaboratoryModelRequestError, load_laboratory_model_config, request_laboratory_model

from .feature_implementations.carriageservice_impl import CarriageServiceImpl
from .feature_implementations.connectionservice_impl import ConnectionServiceImpl
from .feature_implementations.deviceservice_impl import DeviceServiceImpl
from .feature_implementations.labwareservice_impl import LabwareServiceImpl
from .feature_implementations.robotorientationservice_impl import RobotOrientationServiceImpl
from .feature_implementations.robotposeservice_impl import RobotPoseServiceImpl
from .feature_implementations.robotservice_impl import RobotServiceImpl
from .feature_implementations.taskservice_impl import TaskServiceImpl
from .feature_implementations.variableservice_impl import VariableServiceImpl
from .generated.carriageservice import CarriageServiceFeature
from .generated.connectionservice import ConnectionServiceFeature
from .generated.deviceservice import DeviceServiceFeature
from .generated.labwareservice import LabwareServiceFeature
from .generated.robotorientationservice import RobotOrientationServiceFeature
from .generated.robotposeservice import RobotPoseServiceFeature
from .generated.robotservice import RobotServiceFeature
from .generated.taskservice import TaskServiceFeature
from .generated.variableservice import VariableServiceFeature
from .stations import load_station_map

logger = logging.getLogger(__name__)

# --- Command durations. Baked into the image at build time by slicing this device's section out
# --- of the lab-wide duration file (see `tools/slice_durations.py`); a command that is not listed
# --- there waits for nothing.
COMMAND_DURATIONS_FILE = os.getenv("COMMAND_DURATIONS_FILE", "/app/command_durations.json")

# Spacing between two neighbouring stations on the mock's synthetic rail, in millimetres. The
# real machine's stations sit at measured positions taken from its motion configuration, which
# is geometry this world does not model, so the position reported here is the station's index in
# the map times this pitch. See `station_position_mm` for why that is worth reporting at all.
STATION_PITCH_MM = 100.0

# The name of the machine light in the world model: a key in the Ardea device's opaque state
# bag. On the real machine the light is a boolean variable on the robot controller, which has
# no counterpart here, so the world model's device state is where it lives instead -- declared
# by the seed and changeable by an operator (`docs/RULES.md`).
LIGHT_STATE_KEY = "light"


def _load_command_durations(path: str = COMMAND_DURATIONS_FILE) -> dict[str, float]:
    """Read this server's per-command durations, keyed by plain SiLA2 command name.

    A missing file is not an error: a server started outside its image has nothing baked in, and
    the rule for a command with no entry is already "do not wait"."""
    try:
        with open(path, encoding="utf-8") as handle:
            document = json.load(handle)
    except FileNotFoundError:
        logger.info("No command duration file at %s; commands will not wait", path)
        return {}

    commands = document.get("commands") or {}
    return {name: float(entry.get("duration", 0.0)) for name, entry in commands.items()}


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: UUID | None = None,
        name: str | None = None,
        description: str | None = None,
    ):
        # Identity + world wiring from the environment. `laboratory_model_location` is the
        # arm's own transient holding location that a labware passes through mid-transfer.
        env_name = os.getenv("SILA_SERVER_NAME")
        env_type = os.getenv("SILA_SERVER_TYPE")
        # Both world-model settings come from the environment through the shared loader,
        # which rejects a variable that is set but blank or padded. That raises here, during
        # construction, so a misconfigured container fails at startup instead of at its
        # first command.
        laboratory_model = load_laboratory_model_config()
        self.laboratory_model_url = laboratory_model.url
        self.laboratory_model_location = laboratory_model.location
        # The station map: which of this machine's station names means which place in the
        # world. Read and validated here, so a container with a typo in it fails at startup.
        # Unlike the settings above it is not optional -- a transporter that cannot resolve a
        # station name cannot do anything. See `stations.py`.
        self.stations = load_station_map()
        self._command_durations = _load_command_durations()
        # Guards against two commands executing at once; see `executing` below.
        self._execution_lock = Lock()
        self._executing_command: str | None = None

        if name is None:
            name = env_name if env_name else "ArdeaServer"
        if description is None:
            description = (
                "Mock of the Ardea SiLA2 server: a robot arm on a travel carriage that moves "
                "labware between the lab's stations. It serves the real machine's nine Feature "
                "definitions unchanged, but implements only LabwareService.Transfer and the "
                "read-only properties the world model can answer."
            )
        # The server type is the real machine's, because that is the name a client looking for
        # Ardea knows it by; the description above is where being a mock is said out loud.
        server_type = env_type if env_type else "ArdeaSila2Server"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type=server_type,
            server_version="0.1",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        # The nine features, registered in the same order the real server registers them: the
        # b-CAP provider's three, the KV COM+ provider's two, then Ardea's own four.
        self.variableservice = VariableServiceImpl(self)
        self.set_feature_implementation(VariableServiceFeature, self.variableservice)

        self.taskservice = TaskServiceImpl(self)
        self.set_feature_implementation(TaskServiceFeature, self.taskservice)

        self.robotservice = RobotServiceImpl(self)
        self.set_feature_implementation(RobotServiceFeature, self.robotservice)

        self.deviceservice = DeviceServiceImpl(self)
        self.set_feature_implementation(DeviceServiceFeature, self.deviceservice)

        self.connectionservice = ConnectionServiceImpl(self)
        self.set_feature_implementation(ConnectionServiceFeature, self.connectionservice)

        self.robotposeservice = RobotPoseServiceImpl(self)
        self.set_feature_implementation(RobotPoseServiceFeature, self.robotposeservice)

        self.carriageservice = CarriageServiceImpl(self)
        self.set_feature_implementation(CarriageServiceFeature, self.carriageservice)

        self.labwareservice = LabwareServiceImpl(self)
        self.set_feature_implementation(LabwareServiceFeature, self.labwareservice)

        self.robotorientationservice = RobotOrientationServiceImpl(self)
        self.set_feature_implementation(RobotOrientationServiceFeature, self.robotorientationservice)

    @contextmanager
    def executing(self, command_name: str) -> Iterator[None]:
        """Hold this server for one command, refusing a second one that arrives meanwhile.

        A real instrument does one thing at a time, and these mocks keep their internal state in
        plain unsynchronised attributes, so two commands running at once would interleave those
        silently. Long durations make that a realistic possibility rather than a theoretical one.

        The real Ardea enforces the same rule for a blunter reason: its lock makes robot and
        carriage motion mutually exclusive, because two motions at once would collide."""
        with self._execution_lock:
            if self._executing_command is not None:
                raise RuntimeError(
                    f"{command_name} cannot start because {self._executing_command} is still "
                    "executing on this server"
                )
            self._executing_command = command_name
        try:
            yield
        finally:
            with self._execution_lock:
                self._executing_command = None

    def sleep_for(self, command_name: str, *, fraction: float = 1.0) -> None:
        """Wait (part of) the nominal time this command takes on the instrument being mocked.

        A command with no configured duration returns at once -- which also collapses its
        Running window, so a polling client would not observe the transition.

        `fraction` exists for `Transfer`, the one command here that reports progress: it spends
        its configured duration in slices, one per phase, so a subscriber sees the phases
        arrive spread across the transfer instead of all at once at the end. The slices come
        out of that single configured number, so how it is divided does not change the total."""
        duration = self._command_durations.get(command_name, 0.0) * fraction
        if duration > 0:
            time.sleep(duration)

    def _request_laboratory_model(
        self, *, command_name: str, path: str, method: str, payload: dict[str, object] | None = None
    ) -> dict[str, object]:
        """Send one request to the world model, naming the command in any failure.

        Thin wrapper over the shared client: it supplies the configured base URL and turns
        the client's transport error into this server's command-scoped message, which is
        what the feature implementation reports back over SiLA2."""
        if not self.laboratory_model_url:
            raise RuntimeError(f"{command_name} requires LABORATORY_MODEL_URL to be configured")

        try:
            return request_laboratory_model(
                base_url=self.laboratory_model_url,
                path=path,
                method=method,
                payload=payload,
            )
        except LaboratoryModelRequestError as error:
            raise RuntimeError(f"{command_name} failed to access laboratory model: {error}") from error

    def _require_laboratory_model_move_configuration(self, *, command_name: str) -> str:
        """Check the world-model wiring and hand back the arm's own holding location.

        Returning it rather than just validating is what lets `pick_item`/`place_item`
        below pass a definitely-configured location on: the attribute itself is optional,
        because a server may run without the world model wired up."""
        if not self.laboratory_model_url:
            raise RuntimeError(f"{command_name} requires LABORATORY_MODEL_URL to be configured")
        if not self.laboratory_model_location:
            raise RuntimeError(f"{command_name} requires LABORATORY_MODEL_LOCATION to be configured")
        return self.laboratory_model_location

    def move_item(self, *, command_name: str, source: str, destination: str) -> None:
        # Apply a world-model move source -> destination (POST /items/move).
        self._require_laboratory_model_move_configuration(command_name=command_name)
        self._request_laboratory_model(
            command_name=command_name,
            path="/items/move",
            method="POST",
            payload={"source": source, "destination": destination},
        )

    def pick_item(self, *, command_name: str, location: str) -> None:
        # Pick = move the labware from `location` onto the arm's own holding location.
        arm_location = self._require_laboratory_model_move_configuration(command_name=command_name)
        self.move_item(command_name=command_name, source=location, destination=arm_location)

    def place_item(self, *, command_name: str, location: str) -> None:
        # Place = move the labware from the arm's holding location to `location`.
        arm_location = self._require_laboratory_model_move_configuration(command_name=command_name)
        self.move_item(command_name=command_name, source=arm_location, destination=location)

    def station_names(self) -> list[str]:
        """The station names this machine serves, sorted.

        These are the names `Transfer` accepts and `StationNames` reports -- the machine's own
        vocabulary (`Base1`, `Base2`, ...), not world-model locations. Fixed for the server's
        lifetime, as the real property promises, because the map is read once at startup.

        Sorted so every caller sees one ordering: `station_position_mm` turns a station's index
        in this list into a millimetre position, and an index that varied would not be
        reproducible."""
        return sorted(self.stations)

    def station_location(self, station: str) -> str | None:
        """The `device.spot` a station name means, or None if this machine has no such station."""
        return self.stations.get(station)

    def station_position_mm(self, station: str) -> float:
        """The synthetic rail position of `station`.

        The mock has no measured station positions -- the machine's are in its motion
        configuration, which is geometry this world does not model -- so the value is derived
        rather than configured: the station's index in `station_names()`, times
        `STATION_PITCH_MM`. It is not the machine's geometry and is not meant to be read as
        distance. What it gives a client is a number that is stable while nothing moves and
        that *changes when the carriage does*, which is the observable part of the real
        property. An unknown station reports 0.0, the same as the position before the first
        transfer.

        If real positions are ever wanted here, the station map is where they belong, beside
        the location each name already carries."""
        names = self.station_names()
        try:
            return names.index(station) * STATION_PITCH_MM
        except ValueError:
            return 0.0

    def light_is_on(self, *, command_name: str) -> bool:
        """Read the machine light out of the Ardea device's opaque state in the world model.

        Which device to read is decided by the arm's own location, so the light needs no
        configuration of its own: `ardea.gripper` means the light is `ardea`'s `light` key. An
        absent key means off -- the seed is expected to declare it, but a world that never did
        is dark rather than broken."""
        arm_location = self._require_laboratory_model_move_configuration(command_name=command_name)
        device = arm_location.split(".", 1)[0]
        response = self._request_laboratory_model(
            command_name=command_name, path=f"/devices/{device}/state", method="GET"
        )

        state = response.get("state")
        if not isinstance(state, dict):
            raise RuntimeError(f"{command_name} got a laboratory model device-state response without a state map")
        return bool(state.get(LIGHT_STATE_KEY, False))
