# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

import time
from datetime import timedelta
import logging
from queue import Queue
from typing import TYPE_CHECKING, Optional

from sila2.server import MetadataDict, ObservableCommandInstance

from ..generated.plateloccontroller import (
    EnumerateProfiles_Responses,
    PlateLocControllerBase,
    Reset_Responses,
    SetSealingTemperature_Responses,
    SetSealingTime_Responses,
    StartCycle_Responses,
    StopCycle_Responses,
)

if TYPE_CHECKING:
    from ..server import Server


logger = logging.getLogger(__name__)


class PlateLocControllerImpl(PlateLocControllerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

        self.StartCycle_default_lifetime_of_execution = timedelta(minutes=30)
        self.StopCycle_default_lifetime_of_execution = timedelta(minutes=30)
        self.Reset_default_lifetime_of_execution = timedelta(minutes=30)

        self._sealing_temperature = 175
        self._sealing_time = 1.5
        self._actual_temperature = 25
        self._cycle_count = 0
        self._firmware_version = "FW-MOCK-1.0"
        self._version = "PLATELOC-MOCK-1"
        self._profiles = ["default", "foil", "film"]

        self.update_Status(0)
        self.update_Status(1)

    def Status_on_subscription(self, *, metadata: MetadataDict) -> Optional["Queue[int]"]:
        queue = super().Status_on_subscription(metadata=metadata)
        try:
            self.update_Status(self.current_Status, queue=queue)
        except AttributeError:
            self.update_Status(1, queue=queue)
        return queue

    def get_SealingTemperature(self, *, metadata: MetadataDict) -> int:
        return self._sealing_temperature

    def get_SealingTime(self, *, metadata: MetadataDict) -> float:
        return self._sealing_time

    def get_ActualTemperature(self, *, metadata: MetadataDict) -> int:
        return self._actual_temperature

    def get_CycleCount(self, *, metadata: MetadataDict) -> int:
        return self._cycle_count

    def get_FirmwareVersion(self, *, metadata: MetadataDict) -> str:
        return self._firmware_version

    def get_Version(self, *, metadata: MetadataDict) -> str:
        return self._version

    def SetSealingTime(self, SealingTime: float, *, metadata: MetadataDict) -> SetSealingTime_Responses:
        logger.info("PlateLocController.SetSealingTime called: sealing_time=%s", SealingTime)
        if SealingTime <= 0:
            raise ValueError("SealingTime must be > 0")
        self._sealing_time = SealingTime
        return SetSealingTime_Responses()

    def SetSealingTemperature(self, SealingTemperature: int, *, metadata: MetadataDict) -> SetSealingTemperature_Responses:
        logger.info("PlateLocController.SetSealingTemperature called: sealing_temperature=%s", SealingTemperature)
        if SealingTemperature < 0:
            raise ValueError("SealingTemperature must be >= 0")
        self._sealing_temperature = SealingTemperature
        return SetSealingTemperature_Responses()

    def EnumerateProfiles(self, *, metadata: MetadataDict) -> EnumerateProfiles_Responses:
        logger.info("PlateLocController.EnumerateProfiles called")
        return EnumerateProfiles_Responses(self._profiles)

    def StartCycle(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> StartCycle_Responses:
        logger.info("PlateLocController.StartCycle called")
        instance.begin_execution()
        self.update_Status(2)
        try:
            self._actual_temperature = self._sealing_temperature
            time.sleep(0.05)
            self._cycle_count += 1
            return StartCycle_Responses()
        finally:
            self.update_Status(1)

    def StopCycle(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> StopCycle_Responses:
        logger.info("PlateLocController.StopCycle called")
        instance.begin_execution()
        self.update_Status(2)
        try:
            self._actual_temperature = max(25, self._actual_temperature - 5)
            time.sleep(0.05)
            return StopCycle_Responses()
        finally:
            self.update_Status(1)

    def Reset(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Reset_Responses:
        logger.info("PlateLocController.Reset called")
        instance.begin_execution()
        self.update_Status(2)
        try:
            self._sealing_temperature = 175
            self._sealing_time = 1.5
            self._actual_temperature = 25
            self._cycle_count = 0
            time.sleep(0.05)
            return Reset_Responses()
        finally:
            self.update_Status(1)
