# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written mock of the PlateLoc (plate sealer) feature. Follows the feature's status
# contract so it is a drop-in replacement for the real server. It keeps a little internal
# state (sealing temperature/time setpoints, actual temperature, cycle count) exposed via
# getters. StartCycle requires a plate present at this server's location.
#
# Status enum (property `Status`, common to all instruments): 0=Not Connected, 1=Idle,
# 2=Running, 3=Error. Per the XML: StartCycle is Running while sealing then returns to
# Idle; StopCycle/Reset keep their start status then return to Idle; the Set* setters do
# not change Status; every observable command sets Error on a failure during execution.
from __future__ import annotations

import functools
import logging
from collections.abc import Callable
from datetime import timedelta
from queue import Queue
from typing import TYPE_CHECKING, Any

from sila2.server import MetadataDict, ObservableCommandInstance

from ..generated.plateloccontroller import (
    EnumerateProfiles_Responses,
    PlateLocControllerBase,
    Reset_Responses,
    SetSealingTemperature_Responses,
    SetSealingTime_Responses,
    StartCycle_Responses,
    StopCycle_Responses,
)

if TYPE_CHECKING:
    from ..server import Server


logger = logging.getLogger(__name__)


def _one_at_a_time(method: Callable[..., Any]) -> Callable[..., Any]:
    """Refuse to start this command while another one is executing on this server.

    A decorator rather than a `with` block inside every command body: the guard is a property of
    the command rather than four more lines of it, and the command name comes from the method
    itself instead of being repeated. Safe because sila2 invokes an implementation method without
    inspecting its signature.

    Commands whose job is to stop something are deliberately NOT decorated -- making them wait for
    the thing they exist to end would be backwards."""

    @functools.wraps(method)
    def wrapper(self: Any, *args: Any, **kwargs: Any) -> Any:
        with self._server.executing(method.__name__):
            return method(self, *args, **kwargs)

    return wrapper


class PlateLocControllerImpl(PlateLocControllerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._server = parent_server

        # Keep observable command instances pollable well beyond their brief mock runtime.
        self.StartCycle_default_lifetime_of_execution = timedelta(minutes=30)
        self.StopCycle_default_lifetime_of_execution = timedelta(minutes=30)
        self.Reset_default_lifetime_of_execution = timedelta(minutes=30)

        # Sealing setpoints, the (mock) actual temperature, and a cycle counter, all read
        # back through the getters. Fixed mock defaults.
        self._sealing_temperature = 175
        self._sealing_time = 1.5
        self._actual_temperature = 25
        self._cycle_count = 0
        self._firmware_version = "FW-MOCK-1.0"
        self._version = "PLATELOC-MOCK-1"
        self._profiles = ["default", "foil", "film"]

        # Status goes Not Connected (0) -> Idle (1) to mimic a real server coming online.
        self.update_Status(0)
        self.update_Status(1)

    def Status_on_subscription(self, *, metadata: MetadataDict) -> Queue[int] | None:
        # Emit the current status immediately to a new subscriber; fall back to Idle (1).
        queue = super().Status_on_subscription(metadata=metadata)
        try:
            self.update_Status(self.current_Status, queue=queue)
        except AttributeError:
            self.update_Status(1, queue=queue)
        return queue

    # --- Getters: static/state readouts, no status effect. ---

    def get_SealingTemperature(self, *, metadata: MetadataDict) -> int:
        return self._sealing_temperature

    def get_SealingTime(self, *, metadata: MetadataDict) -> float:
        return self._sealing_time

    def get_ActualTemperature(self, *, metadata: MetadataDict) -> int:
        return self._actual_temperature

    def get_CycleCount(self, *, metadata: MetadataDict) -> int:
        return self._cycle_count

    def get_FirmwareVersion(self, *, metadata: MetadataDict) -> str:
        return self._firmware_version

    def get_Version(self, *, metadata: MetadataDict) -> str:
        return self._version

    def SetSealingTime(self, SealingTime: float, *, metadata: MetadataDict) -> SetSealingTime_Responses:
        # Unobservable setter. Per the contract Status is unchanged on success ("same as
        # start"); a bad value is rejected (ValueError) without faulting the instrument.
        logger.info("PlateLocController.SetSealingTime called: sealing_time=%s", SealingTime)
        if SealingTime <= 0:
            raise ValueError("SealingTime must be > 0")
        self._sealing_time = SealingTime
        return SetSealingTime_Responses()

    def SetSealingTemperature(
        self, SealingTemperature: int, *, metadata: MetadataDict
    ) -> SetSealingTemperature_Responses:
        # Unobservable setter; same status semantics as SetSealingTime.
        logger.info("PlateLocController.SetSealingTemperature called: sealing_temperature=%s", SealingTemperature)
        if SealingTemperature < 0:
            raise ValueError("SealingTemperature must be >= 0")
        self._sealing_temperature = SealingTemperature
        return SetSealingTemperature_Responses()

    def EnumerateProfiles(self, *, metadata: MetadataDict) -> EnumerateProfiles_Responses:
        # Unobservable query returning the mock profile names; leaves Status unchanged.
        logger.info("PlateLocController.EnumerateProfiles called")
        return EnumerateProfiles_Responses(self._profiles)

    @_one_at_a_time
    def StartCycle(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> StartCycle_Responses:
        # The sealing cycle: requires a plate present (checked before the run starts, so a
        # missing plate rejects without faulting). Actuating: Running while sealing, Idle
        # on success, Error on failure. Bumps the cycle counter and heats to the setpoint.
        logger.info("PlateLocController.StartCycle called")
        self._server.require_item_at_location(command_name="PlateLocController.StartCycle")
        instance.begin_execution()
        self.update_Status(2)  # Running
        try:
            self._actual_temperature = self._sealing_temperature
            self._server.sleep_for("StartCycle")
            self._cycle_count += 1
            self.update_Status(1)  # normal -> Idle
            return StartCycle_Responses()
        except Exception:
            self.update_Status(3)  # Error
            raise

    def StopCycle(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> StopCycle_Responses:
        # Stop the cycle. Keeps its start status while running (spec: "same as start"),
        # then Idle on success / Error on failure. Cools the mock actual temperature.
        logger.info("PlateLocController.StopCycle called")
        instance.begin_execution()
        try:
            self._actual_temperature = max(25, self._actual_temperature - 5)
            self._server.sleep_for("StopCycle")
            self.update_Status(1)  # normal -> Idle
            return StopCycle_Responses()
        except Exception:
            self.update_Status(3)  # Error
            raise

    @_one_at_a_time
    def Reset(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Reset_Responses:
        # Recover to Idle (e.g. from Error) and restore setpoints/counters to defaults.
        # Keeps start status while running, then Idle on success / Error on failure.
        logger.info("PlateLocController.Reset called")
        instance.begin_execution()
        try:
            self._sealing_temperature = 175
            self._sealing_time = 1.5
            self._actual_temperature = 25
            self._cycle_count = 0
            self._server.sleep_for("Reset")
            self.update_Status(1)  # reset -> Idle
            return Reset_Responses()
        except Exception:
            self.update_Status(3)  # Error
            raise
