# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written beyond the codegen scaffold only in the constructor (server identity from
# the environment). The StationProvider has no world-acting commands, so the laboratory
# model env vars are read for consistency with the other servers but are not used here.

import os
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.stationprovider_impl import StationProviderImpl
from .generated.stationprovider import StationProviderFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: UUID | None = None,
        name: str | None = None,
        description: str | None = None,
    ):
        # Identity from the environment; the laboratory-model vars are unused by this
        # Provider (kept for parity with the instrument servers' constructors).
        env_name = os.getenv("SILA_SERVER_NAME")
        env_type = os.getenv("SILA_SERVER_TYPE")
        self.laboratory_model_url = os.getenv("LABORATORY_MODEL_URL")
        self.laboratory_model_location = os.getenv("LABORATORY_MODEL_LOCATION")

        if name is None:
            name = env_name if env_name else "StationServer"
        if description is None:
            description = "An example SiLA2 server"
        server_type = env_type if env_type else "StationServer"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type=server_type,
            server_version="0.1",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.stationprovider = StationProviderImpl(self)
        self.set_feature_implementation(StationProviderFeature, self.stationprovider)
