# Generated by sila2.code_generator; sila2.__version__: 0.14.0

import os
from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.stationprovider_impl import StationProviderImpl
from .generated.stationprovider import StationProviderFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        env_name = os.getenv("SILA_SERVER_NAME")
        env_type = os.getenv("SILA_SERVER_TYPE")

        if name is None:
            name = env_name if env_name else "StationServer"
        if description is None:
            description = "An example SiLA2 server"
        server_type = env_type if env_type else "StationServer"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type=server_type,
            server_version="0.1",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.stationprovider = StationProviderImpl(self)
        self.set_feature_implementation(StationProviderFeature, self.stationprovider)
