# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written mock of Ardea's CarriageService, the travel carriage the arm rides on. Its two
# properties answer; its one command does not.
#
# `StationNames` is the world model's declared topology minus the arm's own holding spot,
# which is exactly the set of names `LabwareService.Transfer` accepts. On the machine the same
# list comes from the motion configuration.
#
# `CarriagePosition` is a synthetic position -- the station's index in that list times a fixed
# pitch (`Server.station_position_mm`). It is published by `Transfer` as the carriage reaches
# each end of the route, so the property behaves like the real one in the way that matters to a
# client: it is stable while nothing moves and it changes when something does. It is not the
# machine's geometry, and a client should not read distance into it.
#
# `MoveCarriage` refuses. Positioning the carriage on its own has no counterpart in a world
# model that records where labware *is* rather than where the machine is pointed, and the
# transfer that does need the carriage moves it itself.
from __future__ import annotations

import logging
from queue import Queue
from typing import TYPE_CHECKING

from sila2.server import MetadataDict, ObservableCommandInstanceWithIntermediateResponses

from ..generated.carriageservice import (
    CarriageServiceBase,
    MoveCarriage_IntermediateResponses,
    MoveCarriage_Responses,
)
from .unimplemented import unimplemented

if TYPE_CHECKING:
    from ..server import Server


logger = logging.getLogger(__name__)

_FEATURE = "CarriageService"


class CarriageServiceImpl(CarriageServiceBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

        # Publish a starting position, so the observable property has a value from the moment
        # the server is up. Zero is "wherever it was left": the mock does not know where the
        # carriage physically sits until a transfer puts it somewhere, and the real machine
        # would have read the PLC. It is also what an unknown station reports, which keeps the
        # two indistinguishable rather than inventing a third meaning.
        self.update_CarriagePosition(0.0)

    def CarriagePosition_on_subscription(self, *, metadata: MetadataDict) -> Queue[float] | None:
        # Emit the current position immediately to a new subscriber, rather than leaving it
        # waiting for the next transfer to publish one.
        queue = super().CarriagePosition_on_subscription(metadata=metadata)
        try:
            self.update_CarriagePosition(self.current_CarriagePosition, queue=queue)
        except AttributeError:
            self.update_CarriagePosition(0.0, queue=queue)
        return queue

    def get_StationNames(self, *, metadata: MetadataDict) -> list[str]:
        return self.parent_server.station_locations(command_name=f"{_FEATURE}.StationNames")

    def MoveCarriage(
        self,
        StationId: str,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[MoveCarriage_IntermediateResponses],
    ) -> MoveCarriage_Responses:
        unimplemented(_FEATURE, "MoveCarriage")
