# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written mock of Ardea's LabwareService. This is where the one command the mock performs
# lives: `Transfer`, which carries a labware from one station to another. In the world model
# that is two moves through the arm's own location (source -> arm, arm -> destination), which
# is how the trolley arm before it modelled a transfer -- except that the real machine does
# both halves inside a single command, so this mock does too, and a workflow needs one call
# where it used to need two.
#
# `LightIsOn` also answers, out of the Ardea device's opaque state in the world model.
#
# Everything else refuses (see `unimplemented.py`): `PickLabware` / `PutLabware` are the halves
# of a transfer that only make sense with a carriage the mock cannot position and an arm pose
# it does not track, `MoveHand` / `ActivateHand` drive a gripper that has no counterpart here,
# and `ToggleLight` is left out because the decision was to implement the properties and not
# the actuators -- an operator changes the light through the world model instead.
#
# The Feature XML does not describe a status property for this feature, so unlike the
# instrument controllers in this lab there is no Idle/Running bracket to keep: a transfer's
# progress is reported through its intermediate responses, which is what the real server does.
from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from sila2.server import MetadataDict, ObservableCommandInstanceWithIntermediateResponses

from ..generated.labwareservice import (
    ActivateHand_IntermediateResponses,
    ActivateHand_Responses,
    InvalidStation,
    LabwareServiceBase,
    MoveHand_IntermediateResponses,
    MoveHand_Responses,
    PickLabware_IntermediateResponses,
    PickLabware_Responses,
    PutLabware_IntermediateResponses,
    PutLabware_Responses,
    ToggleLight_Responses,
    Transfer_IntermediateResponses,
    Transfer_Responses,
)
from .unimplemented import unimplemented

if TYPE_CHECKING:
    from ..server import Server


logger = logging.getLogger(__name__)

_FEATURE = "LabwareService"

# The phases a transfer reports, in order. Each one is announced and then waited out for an
# equal slice of the command's configured duration, so a subscriber sees them spread across
# the transfer instead of all at once at the end.
#
# The wording follows the real server's phases, but only as far as the mock can honestly go:
# the machine names the PacScript it is running (`approach: RunTask(xxxApproachPick2)`) and
# which way the arm is turned, and this mock knows neither -- there are no task names and no
# arm to turn. Inventing them would put strings in front of a client that look like they came
# from a controller. What is left is the shape of the route, which is the part that is true --
# and the station names, which are the machine's own now that there is a station map.
_PHASE_START = "transfer {source} -> {destination}"
_PHASE_TO_SOURCE = "carriage -> {position:g} mm"
_PHASE_AT_SOURCE = "start (station {station})"
_PHASE_PICK = "chuck: closing hand"
_PHASE_TO_DESTINATION = "carriage -> {position:g} mm"
_PHASE_PUT = "unchuck: opening hand"
_PHASE_VERIFY = "verify retract pose"
_TRANSFER_PHASE_COUNT = 7


class LabwareServiceImpl(LabwareServiceBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

    # ---- the one command this mock performs ----

    def Transfer(
        self,
        SourceStation: str,
        DestinationStation: str,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[Transfer_IntermediateResponses],
    ) -> Transfer_Responses:
        source = str(SourceStation).strip()
        destination = str(DestinationStation).strip()
        logger.info("LabwareService.Transfer called: source=%s destination=%s", source, destination)

        command = f"{_FEATURE}.Transfer"
        # One transfer at a time, for the same reason every other command in this lab is
        # guarded: the mock's state is plain attributes, and two routes interleaving would
        # corrupt them silently. On the machine the same lock keeps two motions from colliding.
        with self.parent_server.executing("Transfer"):
            instance.begin_execution()

            # Resolve both station names against the station map before touching the world.
            # The real server does the same thing first (`station_by_name` ->
            # `InvalidStation`), because a name it does not know is a mistake to report rather
            # than a motion to attempt -- so this is the machine's own behaviour being mocked,
            # not a pre-check invented here.
            source_location = self.parent_server.station_location(source)
            destination_location = self.parent_server.station_location(destination)
            unknown = [
                name
                for name, location in ((source, source_location), (destination, destination_location))
                if location is None
            ]
            if unknown:
                raise InvalidStation(
                    f"{', '.join(unknown)}: not a station of this machine. Known stations: "
                    f"{', '.join(self.parent_server.station_names())}."
                )
            # mypy: the two are not None once `unknown` is empty, but that is not something it
            # can see through the list comprehension above.
            assert source_location is not None and destination_location is not None

            source_position = self.parent_server.station_position_mm(source)
            destination_position = self.parent_server.station_position_mm(destination)

            phases_entered = 0

            def phase(text: str) -> None:
                # Announce, then spend this phase's slice of the configured duration. Sending
                # first and waiting after is what makes the phase visible for the length of
                # time it is supposed to be taking.
                nonlocal phases_entered
                instance.send_intermediate_response(Transfer_IntermediateResponses(Phase=text))
                phases_entered += 1
                # Progress counts phases entered, so the last one leaves it at exactly 1.0.
                # The ignore is a sila2 typing quirk, not a real constraint: `progress` does
                # have a setter, but it is declared after an unrelated property, which mypy
                # reads as the property being read-only.
                instance.progress = phases_entered / _TRANSFER_PHASE_COUNT  # type: ignore[misc]
                self.parent_server.sleep_for("Transfer", fraction=1.0 / _TRANSFER_PHASE_COUNT)

            # The route, in the order the machine drives it: to the source, pick, to the
            # destination, put. The carriage position is published as the carriage arrives, so
            # a client watching that property sees the two legs of the journey.
            phase(_PHASE_START.format(source=source, destination=destination))

            phase(_PHASE_TO_SOURCE.format(position=source_position))
            self.parent_server.carriageservice.update_CarriagePosition(source_position)

            phase(_PHASE_AT_SOURCE.format(station=source))

            phase(_PHASE_PICK)
            self.parent_server.pick_item(command_name=command, location=source_location)

            phase(_PHASE_TO_DESTINATION.format(position=destination_position))
            self.parent_server.carriageservice.update_CarriagePosition(destination_position)

            phase(_PHASE_PUT)
            self.parent_server.place_item(command_name=command, location=destination_location)

            phase(_PHASE_VERIFY)

            # The mock's arm always ends at the destination's retract pose, because there is no
            # motion that could leave it anywhere else -- on the machine this is a genuine
            # readback of the joint angles after the retract task.
            return Transfer_Responses(CarriagePosition=int(destination_position), AtRetractPose=True)

    # ---- the machine light: a read of the world model's device state ----

    def get_LightIsOn(self, *, metadata: MetadataDict) -> bool:
        return self.parent_server.light_is_on(command_name=f"{_FEATURE}.LightIsOn")

    # ---- refused: hardware this world model has no counterpart for ----

    def ToggleLight(self, *, metadata: MetadataDict) -> ToggleLight_Responses:
        unimplemented(_FEATURE, "ToggleLight")

    def PickLabware(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[PickLabware_IntermediateResponses],
    ) -> PickLabware_Responses:
        unimplemented(_FEATURE, "PickLabware")

    def PutLabware(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[PutLabware_IntermediateResponses],
    ) -> PutLabware_Responses:
        unimplemented(_FEATURE, "PutLabware")

    def MoveHand(
        self,
        Position: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[MoveHand_IntermediateResponses],
    ) -> MoveHand_Responses:
        unimplemented(_FEATURE, "MoveHand")

    def ActivateHand(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[ActivateHand_IntermediateResponses],
    ) -> ActivateHand_Responses:
        unimplemented(_FEATURE, "ActivateHand")
