# Generated by sila2.code_generator; sila2.__version__: 0.14.0

from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.greetingprovider_impl import GreetingProviderImpl
from .generated.greetingprovider import GreetingProviderFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        # TODO: fill in your server information
        if name is None:
            name = "ExampleServer"
        if description is None:
            description = "An example SiLA2 server"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type="ExampleServer",
            server_version="0.1",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.greetingprovider = GreetingProviderImpl(self)
        self.set_feature_implementation(GreetingProviderFeature, self.greetingprovider)
