# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written beyond the codegen scaffold: the constructor reads server identity and
# laboratory-model wiring from the environment, and the helper methods below are this
# server's bridge to the shared world model. The feature implementation calls them to
# enforce and apply physical effects (an item must be present; a lid open/close toggles
# the location's accessibility). All world access is best-effort HTTP to the laboratory
# model, and is skipped (with a log line) when the model is not configured.

import json
import logging
import os
from urllib.error import HTTPError, URLError
from urllib.parse import quote
from urllib.request import Request, urlopen
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.automatedthermalcyclercontroller_impl import AutomatedThermalCyclerControllerImpl
from .generated.automatedthermalcyclercontroller import AutomatedThermalCyclerControllerFeature

logger = logging.getLogger(__name__)


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: UUID | None = None,
        name: str | None = None,
        description: str | None = None,
    ):
        # Server identity and world-model wiring come from the environment so compose can
        # configure each instance. `laboratory_model_location` is the single location this
        # instrument acts on (the seam the planned multi-location refactor will generalise).
        env_name = os.getenv("SILA_SERVER_NAME")
        env_type = os.getenv("SILA_SERVER_TYPE")
        self.laboratory_model_url = os.getenv("LABORATORY_MODEL_URL")
        self.laboratory_model_location = os.getenv("LABORATORY_MODEL_LOCATION")

        if name is None:
            name = env_name if env_name else "AutomatedThermalCyclerServer"
        if description is None:
            description = "Mock SiLA2 server for Automated Thermal Cycler"
        server_type = env_type if env_type else "AutomatedThermalCyclerServer"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type=server_type,
            server_version="0.1",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.automatedthermalcyclercontroller = AutomatedThermalCyclerControllerImpl(self)
        self.set_feature_implementation(AutomatedThermalCyclerControllerFeature, self.automatedthermalcyclercontroller)

    def require_item_at_location(self, *, command_name: str) -> None:
        """Precondition check: fail unless an item is present at this server's location.
        Called by commands that physically act on a plate (e.g. StartRun)."""
        # No world configured => nothing to enforce; log and allow (mock convenience).
        if not self.laboratory_model_url or not self.laboratory_model_location:
            logger.info("%s skipped laboratory model occupancy check because configuration is missing", command_name)
            return

        # Read this location's state from the world model. Any lookup failure is treated
        # as a hard error for the command (we cannot confirm the precondition holds).
        encoded_location = quote(self.laboratory_model_location, safe="")
        lookup_url = f"{self.laboratory_model_url.rstrip('/')}/locations/{encoded_location}"
        try:
            with urlopen(lookup_url, timeout=2.0) as response:
                payload = json.load(response)
        except (HTTPError, URLError, TimeoutError, json.JSONDecodeError) as error:
            raise RuntimeError(
                f"{command_name} requires an item at location '{self.laboratory_model_location}', "
                f"but laboratory model lookup failed: {error}"
            ) from error

        if payload.get("occupied") is not True:
            raise RuntimeError(
                f"{command_name} requires an item at location '{self.laboratory_model_location}', "
                "but no item is present"
            )

    def _set_location_accessibility(self, *, command_name: str, accessible: bool) -> None:
        """Push an accessibility change for this server's location to the world model
        (lid/door open => unlock, close => lock). Best-effort; a failure is surfaced as a
        command error so the caller knows the physical effect did not register."""
        if not self.laboratory_model_url or not self.laboratory_model_location:
            logger.info(
                "%s skipped laboratory model accessibility update because configuration is missing",
                command_name,
            )
            return

        endpoint = "/locations/unlock" if accessible else "/locations/lock"
        payload = json.dumps({"location": self.laboratory_model_location}).encode("utf-8")
        request = Request(
            f"{self.laboratory_model_url.rstrip('/')}{endpoint}",
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urlopen(request, timeout=2.0):
                return
        except (HTTPError, URLError, TimeoutError, json.JSONDecodeError) as error:
            raise RuntimeError(
                f"{command_name} failed to update access state for location '{self.laboratory_model_location}': {error}"
            ) from error

    # Named wrappers the feature implementation calls (a lid opening makes the location
    # accessible; closing makes it inaccessible).
    def unlock_location(self, *, command_name: str) -> None:
        self._set_location_accessibility(command_name=command_name, accessible=True)

    def lock_location(self, *, command_name: str) -> None:
        self._set_location_accessibility(command_name=command_name, accessible=False)
