# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written beyond the codegen scaffold: the constructor reads server identity and
# laboratory-model wiring from the environment, and the helper methods below are this
# server's bridge to the shared world model. The feature implementation calls them to
# enforce and apply physical effects (an item must be present; a lid open/close toggles
# the location's accessibility). All world access is best-effort HTTP to the laboratory
# model, and is skipped (with a log line) when the model is not configured.
#
# The HTTP mechanics live in the shared `laboratory_client`; what the world means -- that a
# run needs a plate, that an open lid is a reachable location -- stays here, because the
# interpretation of world state belongs to the command that performs it.
#
# It also owns how long each command waits: the durations are sliced out of the lab-wide
# `config/command_durations.yaml` at image build time and read here, so a command's nominal time
# is configuration rather than a literal buried in the implementation.

import json
import logging
import os
import time
from uuid import UUID, uuid4

from sila2.server import SilaServer

from laboratory_client import (
    LaboratoryModelRequestError,
    get_location,
    load_laboratory_model_config,
    request_laboratory_model,
)

from .feature_implementations.automatedthermalcyclercontroller_impl import AutomatedThermalCyclerControllerImpl
from .generated.automatedthermalcyclercontroller import AutomatedThermalCyclerControllerFeature

logger = logging.getLogger(__name__)

# --- Command durations. Baked into the image at build time by slicing this device's section out
# --- of the lab-wide duration file (see `tools/slice_durations.py`); a command that is not listed
# --- there waits for nothing.
COMMAND_DURATIONS_FILE = os.getenv("COMMAND_DURATIONS_FILE", "/app/command_durations.json")


def _load_command_durations(path: str = COMMAND_DURATIONS_FILE) -> dict[str, float]:
    """Read this server's per-command durations, keyed by plain SiLA2 command name.

    A missing file is not an error: a server started outside its image has nothing baked in, and
    the rule for a command with no entry is already "do not wait"."""
    try:
        with open(path, encoding="utf-8") as handle:
            document = json.load(handle)
    except FileNotFoundError:
        logger.info("No command duration file at %s; commands will not wait", path)
        return {}

    commands = document.get("commands") or {}
    return {name: float(entry.get("duration", 0.0)) for name, entry in commands.items()}


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: UUID | None = None,
        name: str | None = None,
        description: str | None = None,
    ):
        # Server identity and world-model wiring come from the environment so compose can
        # configure each instance. `laboratory_model_location` is the single location this
        # instrument acts on (the seam the planned multi-location refactor will generalise).
        env_name = os.getenv("SILA_SERVER_NAME")
        env_type = os.getenv("SILA_SERVER_TYPE")
        # Both world-model settings come from the environment through the shared loader,
        # which rejects a variable that is set but blank or padded. That raises here, during
        # construction, so a misconfigured container fails at startup instead of at its
        # first command.
        laboratory_model = load_laboratory_model_config()
        self.laboratory_model_url = laboratory_model.url
        self.laboratory_model_location = laboratory_model.location
        self._command_durations = _load_command_durations()

        if name is None:
            name = env_name if env_name else "AutomatedThermalCyclerServer"
        if description is None:
            description = "Mock SiLA2 server for Automated Thermal Cycler"
        server_type = env_type if env_type else "AutomatedThermalCyclerServer"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type=server_type,
            server_version="0.1",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.automatedthermalcyclercontroller = AutomatedThermalCyclerControllerImpl(self)
        self.set_feature_implementation(AutomatedThermalCyclerControllerFeature, self.automatedthermalcyclercontroller)

    def sleep_for(self, command_name: str) -> None:
        """Wait the nominal time this command takes on the instrument being mocked.

        Called by the feature implementation where a fixed sleep used to be. A command with no
        configured duration returns at once -- which also collapses its Running window, so a
        polling client would not observe the Status transition."""
        duration = self._command_durations.get(command_name, 0.0)
        if duration > 0:
            time.sleep(duration)

    def require_item_at_location(self, *, command_name: str) -> None:
        """Precondition check: fail unless an item is present at this server's location.
        Called by commands that physically act on a plate (e.g. StartRun)."""
        # No world configured => nothing to enforce; log and allow (mock convenience).
        if not self.laboratory_model_url or not self.laboratory_model_location:
            logger.info("%s skipped laboratory model occupancy check because configuration is missing", command_name)
            return

        # Read this location's state from the world model. Any lookup failure is treated
        # as a hard error for the command (we cannot confirm the precondition holds).
        try:
            payload = get_location(base_url=self.laboratory_model_url, location=self.laboratory_model_location)
        except LaboratoryModelRequestError as error:
            raise RuntimeError(
                f"{command_name} requires an item at location '{self.laboratory_model_location}', "
                f"but laboratory model lookup failed: {error}"
            ) from error

        if payload.get("occupied") is not True:
            raise RuntimeError(
                f"{command_name} requires an item at location '{self.laboratory_model_location}', "
                "but no item is present"
            )

    def _set_location_accessibility(self, *, command_name: str, accessible: bool) -> None:
        """Push an accessibility change for this server's location to the world model
        (lid/door open => unlock, close => lock). Best-effort; a failure is surfaced as a
        command error so the caller knows the physical effect did not register."""
        if not self.laboratory_model_url or not self.laboratory_model_location:
            logger.info(
                "%s skipped laboratory model accessibility update because configuration is missing",
                command_name,
            )
            return

        # The world model has one endpoint per direction; choosing between them is this
        # server's call, since "the lid is open" is what makes the location reachable.
        endpoint = "/locations/unlock" if accessible else "/locations/lock"
        try:
            request_laboratory_model(
                base_url=self.laboratory_model_url,
                path=endpoint,
                method="POST",
                payload={"location": self.laboratory_model_location},
            )
        except LaboratoryModelRequestError as error:
            raise RuntimeError(
                f"{command_name} failed to update access state for location '{self.laboratory_model_location}': {error}"
            ) from error

    # Named wrappers the feature implementation calls (a lid opening makes the location
    # accessible; closing makes it inaccessible).
    def unlock_location(self, *, command_name: str) -> None:
        self._set_location_accessibility(command_name=command_name, accessible=True)

    def lock_location(self, *, command_name: str) -> None:
        self._set_location_accessibility(command_name=command_name, accessible=False)
