# Generated by sila2.code_generator; sila2.__version__: 0.14.0

import json
import logging
import os
from typing import Optional
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.trolleyarmprovider_impl import TrolleyArmProviderImpl
from .generated.trolleyarmprovider import TrolleyArmProviderFeature


logger = logging.getLogger(__name__)


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        env_name = os.getenv("SILA_SERVER_NAME")
        env_type = os.getenv("SILA_SERVER_TYPE")
        self.laboratory_model_url = os.getenv("LABORATORY_MODEL_URL")
        self.laboratory_model_location = os.getenv("LABORATORY_MODEL_LOCATION")

        if name is None:
            name = env_name if env_name else "TrolleyArmServer"
        if description is None:
            description = "An example SiLA2 server"
        server_type = env_type if env_type else "TrolleyArmServer"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type=server_type,
            server_version="0.1",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.trolleyarmprovider = TrolleyArmProviderImpl(self)
        self.set_feature_implementation(TrolleyArmProviderFeature, self.trolleyarmprovider)

    def _request_laboratory_model(self, *, command_name: str, path: str, method: str, payload: dict[str, object]) -> dict[str, object]:
        if not self.laboratory_model_url:
            raise RuntimeError(f"{command_name} requires LABORATORY_MODEL_URL to be configured")

        request = Request(
            f"{self.laboratory_model_url.rstrip('/')}/{path.lstrip('/')}",
            data=json.dumps(payload).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method=method,
        )
        try:
            with urlopen(request, timeout=2.0) as response:
                return json.load(response)
        except (HTTPError, URLError, TimeoutError, json.JSONDecodeError) as error:
            raise RuntimeError(f"{command_name} failed to access laboratory model: {error}") from error

    def _require_laboratory_model_move_configuration(self, *, command_name: str) -> None:
        if not self.laboratory_model_url:
            raise RuntimeError(f"{command_name} requires LABORATORY_MODEL_URL to be configured")
        if not self.laboratory_model_location:
            raise RuntimeError(f"{command_name} requires LABORATORY_MODEL_LOCATION to be configured")

    def move_item(self, *, command_name: str, source: str, destination: str) -> None:
        self._require_laboratory_model_move_configuration(command_name=command_name)
        self._request_laboratory_model(
            command_name=command_name,
            path="/items/move",
            method="POST",
            payload={"source": source, "destination": destination},
        )

    def pick_item(self, *, command_name: str, location: str) -> None:
        self.move_item(command_name=command_name, source=location, destination=self.laboratory_model_location)

    def place_item(self, *, command_name: str, location: str) -> None:
        self.move_item(command_name=command_name, source=self.laboratory_model_location, destination=location)
