# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written beyond the codegen scaffold: the constructor reads identity + world wiring,
# and the helpers below are the trolley's bridge to the shared world model. Pick/Place are
# modelled as item MOVES through the arm's own location (`laboratory_model_location`):
# Pick = source -> arm, Place = arm -> destination. Unlike the instrument servers this one
# performs moves (not occupancy checks / accessibility toggles), so it requires the world
# model to be configured and raises if it is not (a move has to actually happen).

import json
import logging
import os
from typing import Optional
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.trolleyarmprovider_impl import TrolleyArmProviderImpl
from .generated.trolleyarmprovider import TrolleyArmProviderFeature


logger = logging.getLogger(__name__)


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        # Identity + world wiring from the environment. `laboratory_model_location` is the
        # arm's own transient holding location that items pass through during a transfer.
        env_name = os.getenv("SILA_SERVER_NAME")
        env_type = os.getenv("SILA_SERVER_TYPE")
        self.laboratory_model_url = os.getenv("LABORATORY_MODEL_URL")
        self.laboratory_model_location = os.getenv("LABORATORY_MODEL_LOCATION")

        if name is None:
            name = env_name if env_name else "TrolleyArmServer"
        if description is None:
            description = "An example SiLA2 server"
        server_type = env_type if env_type else "TrolleyArmServer"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type=server_type,
            server_version="0.1",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.trolleyarmprovider = TrolleyArmProviderImpl(self)
        self.set_feature_implementation(TrolleyArmProviderFeature, self.trolleyarmprovider)

    def _request_laboratory_model(self, *, command_name: str, path: str, method: str, payload: dict[str, object]) -> dict[str, object]:
        if not self.laboratory_model_url:
            raise RuntimeError(f"{command_name} requires LABORATORY_MODEL_URL to be configured")

        request = Request(
            f"{self.laboratory_model_url.rstrip('/')}/{path.lstrip('/')}",
            data=json.dumps(payload).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method=method,
        )
        try:
            with urlopen(request, timeout=2.0) as response:
                return json.load(response)
        except (HTTPError, URLError, TimeoutError, json.JSONDecodeError) as error:
            raise RuntimeError(f"{command_name} failed to access laboratory model: {error}") from error

    def _require_laboratory_model_move_configuration(self, *, command_name: str) -> None:
        if not self.laboratory_model_url:
            raise RuntimeError(f"{command_name} requires LABORATORY_MODEL_URL to be configured")
        if not self.laboratory_model_location:
            raise RuntimeError(f"{command_name} requires LABORATORY_MODEL_LOCATION to be configured")

    def move_item(self, *, command_name: str, source: str, destination: str) -> None:
        # Apply a world-model move source -> destination (POST /items/move).
        self._require_laboratory_model_move_configuration(command_name=command_name)
        self._request_laboratory_model(
            command_name=command_name,
            path="/items/move",
            method="POST",
            payload={"source": source, "destination": destination},
        )

    def pick_item(self, *, command_name: str, location: str) -> None:
        # Pick = move the item from `location` onto the arm's own holding location.
        self.move_item(command_name=command_name, source=location, destination=self.laboratory_model_location)

    def place_item(self, *, command_name: str, location: str) -> None:
        # Place = move the item from the arm's holding location to `location`.
        self.move_item(command_name=command_name, source=self.laboratory_model_location, destination=location)
