# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written beyond the codegen scaffold: the constructor reads identity + world wiring,
# and the helpers below are the trolley's bridge to the shared world model. Pick/Place are
# modelled as item MOVES through the arm's own location (`laboratory_model_location`):
# Pick = source -> arm, Place = arm -> destination. Unlike the instrument servers this one
# performs moves (not occupancy checks / accessibility toggles), so it requires the world
# model to be configured and raises if it is not (a move has to actually happen).
#
# The HTTP mechanics live in the shared `laboratory_client` (this server's own generic
# request helper was what that module was extracted from); modelling a transfer as two
# moves through the arm's holding location stays here, because that is this instrument's
# behaviour rather than something the transport should know.
#
# It also owns how long each command waits: the durations are sliced out of the lab-wide
# `config/command_durations.yaml` at image build time and read here, so a command's nominal time
# is configuration rather than a literal buried in the implementation.

import json
import logging
import os
import time
from collections.abc import Iterator
from contextlib import contextmanager
from threading import Lock
from uuid import UUID, uuid4

from sila2.server import SilaServer

from laboratory_client import LaboratoryModelRequestError, load_laboratory_model_config, request_laboratory_model

from .feature_implementations.trolleyarmprovider_impl import TrolleyArmProviderImpl
from .generated.trolleyarmprovider import TrolleyArmProviderFeature

logger = logging.getLogger(__name__)

# --- Command durations. Baked into the image at build time by slicing this device's section out
# --- of the lab-wide duration file (see `tools/slice_durations.py`); a command that is not listed
# --- there waits for nothing.
COMMAND_DURATIONS_FILE = os.getenv("COMMAND_DURATIONS_FILE", "/app/command_durations.json")


def _load_command_durations(path: str = COMMAND_DURATIONS_FILE) -> dict[str, float]:
    """Read this server's per-command durations, keyed by plain SiLA2 command name.

    A missing file is not an error: a server started outside its image has nothing baked in, and
    the rule for a command with no entry is already "do not wait"."""
    try:
        with open(path, encoding="utf-8") as handle:
            document = json.load(handle)
    except FileNotFoundError:
        logger.info("No command duration file at %s; commands will not wait", path)
        return {}

    commands = document.get("commands") or {}
    return {name: float(entry.get("duration", 0.0)) for name, entry in commands.items()}


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: UUID | None = None,
        name: str | None = None,
        description: str | None = None,
    ):
        # Identity + world wiring from the environment. `laboratory_model_location` is the
        # arm's own transient holding location that items pass through during a transfer.
        env_name = os.getenv("SILA_SERVER_NAME")
        env_type = os.getenv("SILA_SERVER_TYPE")
        # Both world-model settings come from the environment through the shared loader,
        # which rejects a variable that is set but blank or padded. That raises here, during
        # construction, so a misconfigured container fails at startup instead of at its
        # first command.
        laboratory_model = load_laboratory_model_config()
        self.laboratory_model_url = laboratory_model.url
        self.laboratory_model_location = laboratory_model.location
        self._command_durations = _load_command_durations()
        # Guards against two commands executing at once; see `executing` below.
        self._execution_lock = Lock()
        self._executing_command: str | None = None

        if name is None:
            name = env_name if env_name else "TrolleyArmServer"
        if description is None:
            description = "An example SiLA2 server"
        server_type = env_type if env_type else "TrolleyArmServer"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type=server_type,
            server_version="0.1",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.trolleyarmprovider = TrolleyArmProviderImpl(self)
        self.set_feature_implementation(TrolleyArmProviderFeature, self.trolleyarmprovider)

    @contextmanager
    def executing(self, command_name: str) -> Iterator[None]:
        """Hold this server for one command, refusing a second one that arrives meanwhile.

        A real instrument does one thing at a time, and these mocks keep their internal state in
        plain unsynchronised attributes, so two commands running at once would interleave those
        silently. Long durations make that a realistic possibility rather than a theoretical one.

        The check is on "is a command executing", NOT on the Status property. StartRun
        deliberately leaves Status at Running until StopRun, so a status-based guard would refuse
        the very command meant to end the run."""
        with self._execution_lock:
            if self._executing_command is not None:
                raise RuntimeError(
                    f"{command_name} cannot start because {self._executing_command} is still "
                    "executing on this server"
                )
            self._executing_command = command_name
        try:
            yield
        finally:
            with self._execution_lock:
                self._executing_command = None

    def sleep_for(self, command_name: str) -> None:
        """Wait the nominal time this command takes on the instrument being mocked.

        Called by the feature implementation where a fixed sleep used to be. A command with no
        configured duration returns at once -- which also collapses its Running window, so a
        polling client would not observe the Status transition."""
        duration = self._command_durations.get(command_name, 0.0)
        if duration > 0:
            time.sleep(duration)

    def _request_laboratory_model(
        self, *, command_name: str, path: str, method: str, payload: dict[str, object]
    ) -> dict[str, object]:
        """Send one request to the world model, naming the command in any failure.

        Thin wrapper over the shared client: it supplies the configured base URL and turns
        the client's transport error into this server's command-scoped message, which is
        what the feature implementation reports back over SiLA2."""
        if not self.laboratory_model_url:
            raise RuntimeError(f"{command_name} requires LABORATORY_MODEL_URL to be configured")

        try:
            return request_laboratory_model(
                base_url=self.laboratory_model_url,
                path=path,
                method=method,
                payload=payload,
            )
        except LaboratoryModelRequestError as error:
            raise RuntimeError(f"{command_name} failed to access laboratory model: {error}") from error

    def _require_laboratory_model_move_configuration(self, *, command_name: str) -> str:
        """Check the world-model wiring and hand back the arm's own holding location.

        Returning it rather than just validating is what lets `pick_item`/`place_item`
        below pass a definitely-configured location on: the attribute itself is optional,
        because a server may run without the world model wired up."""
        if not self.laboratory_model_url:
            raise RuntimeError(f"{command_name} requires LABORATORY_MODEL_URL to be configured")
        if not self.laboratory_model_location:
            raise RuntimeError(f"{command_name} requires LABORATORY_MODEL_LOCATION to be configured")
        return self.laboratory_model_location

    def move_item(self, *, command_name: str, source: str, destination: str) -> None:
        # Apply a world-model move source -> destination (POST /items/move).
        self._require_laboratory_model_move_configuration(command_name=command_name)
        self._request_laboratory_model(
            command_name=command_name,
            path="/items/move",
            method="POST",
            payload={"source": source, "destination": destination},
        )

    def pick_item(self, *, command_name: str, location: str) -> None:
        # Pick = move the item from `location` onto the arm's own holding location.
        arm_location = self._require_laboratory_model_move_configuration(command_name=command_name)
        self.move_item(command_name=command_name, source=location, destination=arm_location)

    def place_item(self, *, command_name: str, location: str) -> None:
        # Place = move the item from the arm's holding location to `location`.
        arm_location = self._require_laboratory_model_move_configuration(command_name=command_name)
        self.move_item(command_name=command_name, source=arm_location, destination=location)
