# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written mock of the automated plate seal remover (peeler) feature. Follows the
# feature's status contract so it is a drop-in replacement for the real server. It tracks
# two tape spool reserves (supply/take-up), decremented per Peel and reported by
# GetTapeLeft. Peel requires a plate present at this server's location.
#
# Status enum (property `Status`, common to all instruments): 0=Not Connected, 1=Idle,
# 2=Running, 3=Error. Per the XML: Peel and ResetInstrument are Running while acting then
# return to Idle; GetTapeLeft keeps the start status (a read); Reset keeps its start status
# then returns to Idle; every observable command sets Error on a failure during execution.
from __future__ import annotations

import time
from datetime import timedelta
import logging
from queue import Queue
from typing import TYPE_CHECKING, Optional

from sila2.server import MetadataDict, ObservableCommandInstance

from ..generated.automatedplatesealremovercontroller import (
    AutomatedPlateSealRemoverControllerBase,
    GetTapeLeft_Responses,
    Peel_Responses,
    Reset_Responses,
    ResetInstrument_Responses,
)

if TYPE_CHECKING:
    from ..server import Server


logger = logging.getLogger(__name__)


class AutomatedPlateSealRemoverControllerImpl(AutomatedPlateSealRemoverControllerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._server = parent_server

        # Keep observable command instances pollable well beyond their brief mock runtime.
        self.Peel_default_lifetime_of_execution = timedelta(minutes=30)
        self.GetTapeLeft_default_lifetime_of_execution = timedelta(minutes=30)
        self.ResetInstrument_default_lifetime_of_execution = timedelta(minutes=30)
        self.Reset_default_lifetime_of_execution = timedelta(minutes=30)

        # Mock tape reserves for the supply and take-up spools (arbitrary starting count;
        # one unit is consumed per Peel). GetTapeLeft reports these and warns when low.
        self._supply_spool_remaining = 1200
        self._takeup_spool_remaining = 1200

        # Status goes Not Connected (0) -> Idle (1) to mimic a real server coming online.
        self.update_Status(0)
        self.update_Status(1)

    def Status_on_subscription(self, *, metadata: MetadataDict) -> Optional["Queue[int]"]:
        # Emit the current status immediately to a new subscriber; fall back to Idle (1).
        queue = super().Status_on_subscription(metadata=metadata)
        try:
            self.update_Status(self.current_Status, queue=queue)
        except AttributeError:
            self.update_Status(1, queue=queue)
        return queue

    def Peel(
        self,
        BeginPeelLocation: int,
        AdhesionTime: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Peel_Responses:
        # Peel the seal off the plate. Inputs are validated and a plate is required before
        # the run starts (a bad input / missing plate rejects without faulting). Actuating:
        # Running while peeling, Idle on success, Error on failure. Consumes one unit of
        # tape from each spool and returns a LOW_TAPE warning when the supply runs low.
        logger.info(
            "AutomatedPlateSealRemoverController.Peel called: begin_peel_location=%s adhesion_time=%s",
            BeginPeelLocation,
            AdhesionTime,
        )
        if not (1 <= BeginPeelLocation <= 9):
            raise ValueError("BeginPeelLocation must be in range 1..9")
        if not (1 <= AdhesionTime <= 4):
            raise ValueError("AdhesionTime must be in range 1..4")
        self._server.require_item_at_location(command_name="AutomatedPlateSealRemoverController.Peel")

        instance.begin_execution()
        self.update_Status(2)  # Running
        try:
            time.sleep(0.05)
            self._supply_spool_remaining = max(0, self._supply_spool_remaining - 1)
            self._takeup_spool_remaining = max(0, self._takeup_spool_remaining - 1)
            warning = "LOW_TAPE" if self._supply_spool_remaining < 25 else ""
            self.update_Status(1)  # normal -> Idle
            return Peel_Responses(warning)
        except Exception:
            self.update_Status(3)  # Error
            raise

    def GetTapeLeft(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> GetTapeLeft_Responses:
        # Value-returning read of the two spool reserves (+ LOW_TAPE warning). Per the
        # contract Status is unchanged on success ("same as start"); a failure sets Error.
        logger.info("AutomatedPlateSealRemoverController.GetTapeLeft called")
        instance.begin_execution()
        try:
            warning = "LOW_TAPE" if self._supply_spool_remaining < 25 else ""
            return GetTapeLeft_Responses(
                self._supply_spool_remaining,
                self._takeup_spool_remaining,
                warning,
            )
        except Exception:
            self.update_Status(3)  # Error
            raise

    def ResetInstrument(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> ResetInstrument_Responses:
        # Actuating recovery command: Running while acting, Idle on success, Error on
        # failure. (Distinct from Reset below, which keeps its start status.)
        logger.info("AutomatedPlateSealRemoverController.ResetInstrument called")
        instance.begin_execution()
        self.update_Status(2)  # Running
        try:
            time.sleep(0.05)
            self.update_Status(1)  # normal -> Idle
            return ResetInstrument_Responses("")
        except Exception:
            self.update_Status(3)  # Error
            raise

    def Reset(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Reset_Responses:
        # Recover to Idle and refill the tape reserves. Keeps its start status while
        # running, then Idle on success / Error on failure.
        logger.info("AutomatedPlateSealRemoverController.Reset called")
        instance.begin_execution()
        try:
            time.sleep(0.05)
            self._supply_spool_remaining = 1200
            self._takeup_spool_remaining = 1200
            self.update_Status(1)  # reset -> Idle
            return Reset_Responses("")
        except Exception:
            self.update_Status(3)  # Error
            raise
