# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

import time
from datetime import timedelta
from queue import Queue
from typing import TYPE_CHECKING, Optional

from sila2.server import MetadataDict, ObservableCommandInstance

from ..generated.automatedplatesealremovercontroller import (
    AutomatedPlateSealRemoverControllerBase,
    GetTapeLeft_Responses,
    Peel_Responses,
    Reset_Responses,
    ResetInstrument_Responses,
)

if TYPE_CHECKING:
    from ..server import Server


class AutomatedPlateSealRemoverControllerImpl(AutomatedPlateSealRemoverControllerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

        self.Peel_default_lifetime_of_execution = timedelta(minutes=30)
        self.GetTapeLeft_default_lifetime_of_execution = timedelta(minutes=30)
        self.ResetInstrument_default_lifetime_of_execution = timedelta(minutes=30)
        self.Reset_default_lifetime_of_execution = timedelta(minutes=30)

        self._supply_spool_remaining = 1200
        self._takeup_spool_remaining = 1200

        self.update_Status(0)
        self.update_Status(1)

    def Status_on_subscription(self, *, metadata: MetadataDict) -> Optional["Queue[int]"]:
        queue = super().Status_on_subscription(metadata=metadata)
        try:
            self.update_Status(self.current_Status, queue=queue)
        except AttributeError:
            self.update_Status(1, queue=queue)
        return queue

    def Peel(
        self,
        BeginPeelLocation: int,
        AdhesionTime: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Peel_Responses:
        if not (1 <= BeginPeelLocation <= 9):
            raise ValueError("BeginPeelLocation must be in range 1..9")
        if not (1 <= AdhesionTime <= 4):
            raise ValueError("AdhesionTime must be in range 1..4")

        instance.begin_execution()
        self.update_Status(2)
        try:
            time.sleep(0.05)
            self._supply_spool_remaining = max(0, self._supply_spool_remaining - 1)
            self._takeup_spool_remaining = max(0, self._takeup_spool_remaining - 1)
            warning = "LOW_TAPE" if self._supply_spool_remaining < 25 else ""
            return Peel_Responses(warning)
        finally:
            self.update_Status(1)

    def GetTapeLeft(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> GetTapeLeft_Responses:
        instance.begin_execution()
        warning = "LOW_TAPE" if self._supply_spool_remaining < 25 else ""
        return GetTapeLeft_Responses(
            self._supply_spool_remaining,
            self._takeup_spool_remaining,
            warning,
        )

    def ResetInstrument(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> ResetInstrument_Responses:
        instance.begin_execution()
        self.update_Status(2)
        try:
            time.sleep(0.05)
            return ResetInstrument_Responses("")
        finally:
            self.update_Status(1)

    def Reset(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Reset_Responses:
        instance.begin_execution()
        self.update_Status(2)
        try:
            time.sleep(0.05)
            self._supply_spool_remaining = 1200
            self._takeup_spool_remaining = 1200
            return Reset_Responses("")
        finally:
            self.update_Status(1)
