# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.greetingprovider import GreetingProviderBase, SayHello_Responses

if TYPE_CHECKING:
    from ..server import Server


class GreetingProviderImpl(GreetingProviderBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

    def get_StartYear(self, *, metadata: MetadataDict) -> int:
        return 2022

    def SayHello(self, Name: str, *, metadata: MetadataDict) -> SayHello_Responses:
        return SayHello_Responses(Greeting="Hello " + Name)
