# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written beyond the codegen scaffold: the constructor reads server identity and
# laboratory-model wiring from the environment, and `require_item_at_location` is this
# server's precondition bridge to the shared world model (StartCycle needs a plate
# present). This instrument has no lid/door, so there is no accessibility control here.
# The world lookup is best-effort HTTP, skipped (with a log line) when unconfigured.
#
# The HTTP mechanics live in the shared `laboratory_client`; reading occupancy as "a plate
# is ready to be sealed" stays here, because the interpretation of world state belongs to
# the command that performs it.
#
# It also owns how long each command waits: the durations are sliced out of the lab-wide
# `config/command_durations.yaml` at image build time and read here, so a command's nominal time
# is configuration rather than a literal buried in the implementation.

import json
import logging
import os
import time
from uuid import UUID, uuid4

from sila2.server import SilaServer

from laboratory_client import LaboratoryModelRequestError, get_location, load_laboratory_model_config

from .feature_implementations.plateloccontroller_impl import PlateLocControllerImpl
from .generated.plateloccontroller import PlateLocControllerFeature

logger = logging.getLogger(__name__)

# --- Command durations. Baked into the image at build time by slicing this device's section out
# --- of the lab-wide duration file (see `tools/slice_durations.py`); a command that is not listed
# --- there waits for nothing.
COMMAND_DURATIONS_FILE = os.getenv("COMMAND_DURATIONS_FILE", "/app/command_durations.json")


def _load_command_durations(path: str = COMMAND_DURATIONS_FILE) -> dict[str, float]:
    """Read this server's per-command durations, keyed by plain SiLA2 command name.

    A missing file is not an error: a server started outside its image has nothing baked in, and
    the rule for a command with no entry is already "do not wait"."""
    try:
        with open(path, encoding="utf-8") as handle:
            document = json.load(handle)
    except FileNotFoundError:
        logger.info("No command duration file at %s; commands will not wait", path)
        return {}

    commands = document.get("commands") or {}
    return {name: float(entry.get("duration", 0.0)) for name, entry in commands.items()}


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: UUID | None = None,
        name: str | None = None,
        description: str | None = None,
    ):
        # Server identity and world-model wiring come from the environment so compose can
        # configure each instance. `laboratory_model_location` is the single location this
        # instrument acts on (the seam the planned multi-location refactor will generalise).
        env_name = os.getenv("SILA_SERVER_NAME")
        env_type = os.getenv("SILA_SERVER_TYPE")
        # Both world-model settings come from the environment through the shared loader,
        # which rejects a variable that is set but blank or padded. That raises here, during
        # construction, so a misconfigured container fails at startup instead of at its
        # first command.
        laboratory_model = load_laboratory_model_config()
        self.laboratory_model_url = laboratory_model.url
        self.laboratory_model_location = laboratory_model.location
        self._command_durations = _load_command_durations()

        if name is None:
            name = env_name if env_name else "PlateLocServer"
        if description is None:
            description = "Mock SiLA2 server for PlateLoc"
        server_type = env_type if env_type else "PlateLocServer"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type=server_type,
            server_version="0.1",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.plateloccontroller = PlateLocControllerImpl(self)
        self.set_feature_implementation(PlateLocControllerFeature, self.plateloccontroller)

    def sleep_for(self, command_name: str) -> None:
        """Wait the nominal time this command takes on the instrument being mocked.

        Called by the feature implementation where a fixed sleep used to be. A command with no
        configured duration returns at once -- which also collapses its Running window, so a
        polling client would not observe the Status transition."""
        duration = self._command_durations.get(command_name, 0.0)
        if duration > 0:
            time.sleep(duration)

    def require_item_at_location(self, *, command_name: str) -> None:
        """Precondition check: fail unless an item is present at this server's location.
        Called by commands that physically act on a plate (e.g. StartCycle)."""
        # No world configured => nothing to enforce; log and allow (mock convenience).
        if not self.laboratory_model_url or not self.laboratory_model_location:
            logger.info("%s skipped laboratory model occupancy check because configuration is missing", command_name)
            return

        # Read this location's state from the world model. Any lookup failure is treated
        # as a hard error for the command (we cannot confirm the precondition holds).
        try:
            payload = get_location(base_url=self.laboratory_model_url, location=self.laboratory_model_location)
        except LaboratoryModelRequestError as error:
            raise RuntimeError(
                f"{command_name} requires an item at location '{self.laboratory_model_location}', "
                f"but laboratory model lookup failed: {error}"
            ) from error

        if payload.get("occupied") is not True:
            raise RuntimeError(
                f"{command_name} requires an item at location '{self.laboratory_model_location}', "
                "but no item is present"
            )
