# Generated by sila2.code_generator; sila2.__version__: 0.14.0

import os
from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.plateloccontroller_impl import PlateLocControllerImpl
from .generated.plateloccontroller import PlateLocControllerFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        env_name = os.getenv("SILA_SERVER_NAME")
        env_type = os.getenv("SILA_SERVER_TYPE")

        if name is None:
            name = env_name if env_name else "PlateLocServer"
        if description is None:
            description = "Mock SiLA2 server for PlateLoc"
        server_type = env_type if env_type else "PlateLocServer"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type=server_type,
            server_version="0.1",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.plateloccontroller = PlateLocControllerImpl(self)
        self.set_feature_implementation(PlateLocControllerFeature, self.plateloccontroller)
