# Generated by sila2.code_generator; sila2.__version__: 0.14.0
#
# Hand-written beyond the codegen scaffold: the constructor reads server identity and
# laboratory-model wiring from the environment, and `require_item_at_location` is this
# server's precondition bridge to the shared world model (StartCycle needs a plate
# present). This instrument has no lid/door, so there is no accessibility control here.
# The world lookup is best-effort HTTP, skipped (with a log line) when unconfigured.
#
# The HTTP mechanics live in the shared `laboratory_client`; reading occupancy as "a plate
# is ready to be sealed" stays here, because the interpretation of world state belongs to
# the command that performs it.

import logging
import os
from uuid import UUID, uuid4

from sila2.server import SilaServer

from laboratory_client import LaboratoryModelRequestError, get_location

from .feature_implementations.plateloccontroller_impl import PlateLocControllerImpl
from .generated.plateloccontroller import PlateLocControllerFeature

logger = logging.getLogger(__name__)


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: UUID | None = None,
        name: str | None = None,
        description: str | None = None,
    ):
        # Server identity and world-model wiring come from the environment so compose can
        # configure each instance. `laboratory_model_location` is the single location this
        # instrument acts on (the seam the planned multi-location refactor will generalise).
        env_name = os.getenv("SILA_SERVER_NAME")
        env_type = os.getenv("SILA_SERVER_TYPE")
        self.laboratory_model_url = os.getenv("LABORATORY_MODEL_URL")
        self.laboratory_model_location = os.getenv("LABORATORY_MODEL_LOCATION")

        if name is None:
            name = env_name if env_name else "PlateLocServer"
        if description is None:
            description = "Mock SiLA2 server for PlateLoc"
        server_type = env_type if env_type else "PlateLocServer"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type=server_type,
            server_version="0.1",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.plateloccontroller = PlateLocControllerImpl(self)
        self.set_feature_implementation(PlateLocControllerFeature, self.plateloccontroller)

    def require_item_at_location(self, *, command_name: str) -> None:
        """Precondition check: fail unless an item is present at this server's location.
        Called by commands that physically act on a plate (e.g. StartCycle)."""
        # No world configured => nothing to enforce; log and allow (mock convenience).
        if not self.laboratory_model_url or not self.laboratory_model_location:
            logger.info("%s skipped laboratory model occupancy check because configuration is missing", command_name)
            return

        # Read this location's state from the world model. Any lookup failure is treated
        # as a hard error for the command (we cannot confirm the precondition holds).
        try:
            payload = get_location(base_url=self.laboratory_model_url, location=self.laboratory_model_location)
        except LaboratoryModelRequestError as error:
            raise RuntimeError(
                f"{command_name} requires an item at location '{self.laboratory_model_location}', "
                f"but laboratory model lookup failed: {error}"
            ) from error

        if payload.get("occupied") is not True:
            raise RuntimeError(
                f"{command_name} requires an item at location '{self.laboratory_model_location}', "
                "but no item is present"
            )
